export class BffError extends Error { constructor(readonly code: "UNAUTHENTICATED" | "SESSION_REVOKED" | "CSRF_INVALID" | "RELEASE_ENVELOPE_INVALID" | "TURN_UNAVAILABLE" | "CITATION_DENIED") { super(code); } }
export interface SessionContext { subjectRef: string; sessionId: string; deviceRef: string; sessionRevision: number; navigationCapabilities: readonly string[]; }
export interface BffSessionPort { validate(input: { sessionId: string; deviceRef: string; clientKeyRef: string; csrfToken: string }): SessionContext; }
export interface ReleaseEnvelope { requestId: string; turnId: string; callerWorkloadRef: "product-bff"; outputDigest: string; byteLength: number; expiresAt: number; derivedDisclosureRef: string; auditReceipt: string; finalizationRef: string; exposureCommitRef: string; signature: string; }
export interface ReleaseVerifier { verify(envelope: ReleaseEnvelope): boolean; digest(output: string): string; }
export interface MemoryAdapter { status(input: { requestId: string; subjectRef: string; turnId: string }): { state: string; turnId: string; conversationId: string }; redisclose(input: { requestId: string; subjectRef: string; turnId: string; deviceRef: string; purposeRef: string }): { output: string; outputDigest: string; citationRefs: readonly string[]; }; }
export interface CitationAdapter { resolve(input: { requestId: string; subjectRef: string; deviceRef: string; citationRef: string }): { citationRef: string; title: string; versionRef: string; snippet: string }; }
export interface NavigationManifest { subjectRef: string; capabilities: readonly string[]; }
export type BffEvent = { type: "progress"; turnId: string; state: string } | { type: "final"; turnId: string; output: string; citations: readonly string[] };

/** Browser-facing adapter: no local output cache, notifications, or client-provided authorization claims. */
export class EmployeeBff {
  constructor(private readonly sessions: BffSessionPort, private readonly releases: ReleaseVerifier, private readonly memory: MemoryAdapter, private readonly citations: CitationAdapter, private readonly now = () => Date.now()) {}
  navigation(input: { sessionId: string; deviceRef: string; clientKeyRef: string; csrfToken: string }): NavigationManifest { const session = this.session(input); return { subjectRef: session.subjectRef, capabilities: [...session.navigationCapabilities] }; }
  progress(input: { sessionId: string; deviceRef: string; clientKeyRef: string; csrfToken: string; turnId: string; state: string }): BffEvent { this.session(input); return { type: "progress", turnId: input.turnId, state: input.state }; }
  release(input: { sessionId: string; deviceRef: string; clientKeyRef: string; csrfToken: string; requestId: string; output: string; envelope: ReleaseEnvelope; citations: readonly string[] }): BffEvent { this.session(input); if (!this.releases.verify(input.envelope) || input.envelope.requestId !== input.requestId || input.envelope.callerWorkloadRef !== "product-bff" || input.envelope.expiresAt <= this.now() || this.releases.digest(input.output) !== input.envelope.outputDigest || new TextEncoder().encode(input.output).byteLength !== input.envelope.byteLength || !input.envelope.derivedDisclosureRef || !input.envelope.auditReceipt || !input.envelope.finalizationRef || !input.envelope.exposureCommitRef) throw new BffError("RELEASE_ENVELOPE_INVALID"); return { type: "final", turnId: input.envelope.turnId, output: input.output, citations: [...input.citations] }; }
  reopen(input: { sessionId: string; deviceRef: string; clientKeyRef: string; csrfToken: string; requestId: string; turnId: string; purposeRef: string }): BffEvent { const session = this.session(input); const status = this.memory.status({ requestId: input.requestId, subjectRef: session.subjectRef, turnId: input.turnId }); if (status.state !== "COMPLETED") throw new BffError("TURN_UNAVAILABLE"); const output = this.memory.redisclose({ requestId: input.requestId, subjectRef: session.subjectRef, turnId: input.turnId, deviceRef: session.deviceRef, purposeRef: input.purposeRef }); if (this.releases.digest(output.output) !== output.outputDigest) throw new BffError("RELEASE_ENVELOPE_INVALID"); return { type: "final", turnId: input.turnId, output: output.output, citations: [...output.citationRefs] }; }
  citation(input: { sessionId: string; deviceRef: string; clientKeyRef: string; csrfToken: string; requestId: string; citationRef: string }): { citationRef: string; title: string; versionRef: string; snippet: string } { const session = this.session(input); try { return this.citations.resolve({ requestId: input.requestId, subjectRef: session.subjectRef, deviceRef: session.deviceRef, citationRef: input.citationRef }); } catch { throw new BffError("CITATION_DENIED"); } }
  private session(input: { sessionId: string; deviceRef: string; clientKeyRef: string; csrfToken: string }): SessionContext { try { if (!input.csrfToken) throw new Error("csrf"); return this.sessions.validate(input); } catch { throw new BffError("UNAUTHENTICATED"); } }
}
