export type RetrievalMode = "lexical" | "semantic" | "graph" | "hybrid" | "structured" | "citation_refresh";
export type RetrievalOutcome = "completed" | "no_context" | "denied_policy" | "failed_downstream" | "cancelled_deadline" | "overloaded";
export class RetrievalError extends Error { constructor(readonly code: "INVALID_REQUEST" | "AUTHORIZATION_UNAVAILABLE" | "AUDIT_UNAVAILABLE" | "DEPENDENCY_UNAVAILABLE") { super(code); } }
export interface Candidate { resourceRef: string; versionRef: string; chunkRef: string; contentHash: string; lane: "lexical" | "vector" | "graph" | "metadata"; rank: number; }
export interface RetrievedChunk { resourceRef: string; versionRef: string; chunkRef: string; contentHash: string; text: string; citationAnchor: string; }
export interface RetrievalPdp { authorizeOperation(input: { requestId: string; subjectRef: string; deviceRef: string; corpusRef: string; mode: RetrievalMode; deadlineAt: number }): { allowed: boolean; decisionRef: string }; authorizeBatch(input: { requestId: string; subjectRef: string; deviceRef: string; resourceRefs: readonly string[]; intentDigest: string; deadlineAt: number }): { allowedRefs: readonly string[]; decisionRef: string; fence?: string; revisionDigest: string }; }
export interface RetrievalIndexes { search(input: { mode: RetrievalMode; queryDigest: string; corpusRef: string; limit: number }): readonly Candidate[]; }
export interface AuthorizedContentStore { fetch(input: { requestId: string; callerWorkloadRef: "retrieval"; fence: string; resources: readonly Pick<Candidate, "resourceRef" | "versionRef" | "chunkRef" | "contentHash">[] }): readonly RetrievedChunk[]; }
export interface RetrievalAudit { admit(input: { requestId: string; operationDecisionRef: string; candidateDecisionRef: string; candidateDigest: string; allowedDigest: string; manifestDigest: string }): { receipt: string }; }
export interface ContextManifest { requestId: string; resourceRefs: readonly string[]; versionRefs: readonly string[]; chunkRefs: readonly string[]; contentHashes: readonly string[]; packagedContextDigest: string; operationDecisionRef: string; candidateDecisionRef: string; revisionDigest: string; purpose: "retrieval"; }
export interface RetrievalResponse { outcome: RetrievalOutcome; chunks: readonly RetrievedChunk[]; manifest?: ContextManifest; auditReceipt?: string; }

/** Query-time retrieval only: indexes narrow candidates; PDP and immutable fenced fetch authorize bytes. */
export class HybridRetrievalService {
  constructor(private readonly pdp: RetrievalPdp, private readonly indexes: RetrievalIndexes, private readonly content: AuthorizedContentStore, private readonly audit: RetrievalAudit, private readonly now = () => Date.now()) {}
  retrieve(input: { requestId: string; subjectRef: string; deviceRef: string; corpusRef: string; mode: RetrievalMode; queryDigest: string; deadlineAt: number; candidateLimit?: number }): RetrievalResponse {
    const limit = input.candidateLimit ?? 100; if (!input.requestId || !input.subjectRef || !input.deviceRef || !input.corpusRef || !input.queryDigest || limit < 1 || limit > 1000) throw new RetrievalError("INVALID_REQUEST"); if (input.deadlineAt <= this.now()) return { outcome: "cancelled_deadline", chunks: [] };
    let operation; try { operation = this.pdp.authorizeOperation(input); } catch { throw new RetrievalError("AUTHORIZATION_UNAVAILABLE"); } if (!operation.allowed) return { outcome: "denied_policy", chunks: [] };
    if (input.deadlineAt <= this.now()) return { outcome: "cancelled_deadline", chunks: [] }; let candidates: readonly Candidate[]; try { candidates = this.merge(this.indexes.search({ mode: input.mode, queryDigest: input.queryDigest, corpusRef: input.corpusRef, limit })); } catch { throw new RetrievalError("DEPENDENCY_UNAVAILABLE"); } if (candidates.length === 0) return { outcome: "no_context", chunks: [] };
    const candidateDigest = candidates.map((candidate) => `${candidate.resourceRef}@${candidate.versionRef}#${candidate.chunkRef}:${candidate.contentHash}`).join("|"); let decision; try { decision = this.pdp.authorizeBatch({ requestId: input.requestId, subjectRef: input.subjectRef, deviceRef: input.deviceRef, resourceRefs: candidates.map((candidate) => candidate.versionRef), intentDigest: candidateDigest, deadlineAt: input.deadlineAt }); } catch { throw new RetrievalError("AUTHORIZATION_UNAVAILABLE"); }
    const allowed = candidates.filter((candidate) => decision.allowedRefs.includes(candidate.versionRef)); if (allowed.length === 0 || !decision.fence) return { outcome: "no_context", chunks: [] }; if (input.deadlineAt <= this.now()) return { outcome: "cancelled_deadline", chunks: [] };
    let chunks: readonly RetrievedChunk[]; try { chunks = this.content.fetch({ requestId: input.requestId, callerWorkloadRef: "retrieval", fence: decision.fence, resources: allowed.map(({ resourceRef, versionRef, chunkRef, contentHash }) => ({ resourceRef, versionRef, chunkRef, contentHash })) }); } catch { throw new RetrievalError("DEPENDENCY_UNAVAILABLE"); }
    const chunkKeys = new Set(chunks.map((chunk) => `${chunk.resourceRef}|${chunk.versionRef}|${chunk.chunkRef}|${chunk.contentHash}`)); if (chunks.length === 0 || chunks.length > allowed.length || chunkKeys.size !== chunks.length || chunks.some((chunk) => !allowed.some((candidate) => candidate.resourceRef === chunk.resourceRef && candidate.versionRef === chunk.versionRef && candidate.chunkRef === chunk.chunkRef && candidate.contentHash === chunk.contentHash))) return { outcome: "no_context", chunks: [] };
    const ordered = chunks.slice().sort((a, b) => this.score(allowed, a) - this.score(allowed, b)); const manifest: ContextManifest = { requestId: input.requestId, resourceRefs: ordered.map((chunk) => chunk.resourceRef), versionRefs: ordered.map((chunk) => chunk.versionRef), chunkRefs: ordered.map((chunk) => chunk.chunkRef), contentHashes: ordered.map((chunk) => chunk.contentHash), packagedContextDigest: ordered.map((chunk) => `${chunk.resourceRef}@${chunk.versionRef}#${chunk.chunkRef}:${chunk.contentHash}`).join("|"), operationDecisionRef: operation.decisionRef, candidateDecisionRef: decision.decisionRef, revisionDigest: decision.revisionDigest, purpose: "retrieval" };
    let receipt; try { receipt = this.audit.admit({ requestId: input.requestId, operationDecisionRef: operation.decisionRef, candidateDecisionRef: decision.decisionRef, candidateDigest, allowedDigest: ordered.map((chunk) => `${chunk.resourceRef}@${chunk.versionRef}#${chunk.chunkRef}:${chunk.contentHash}`).join("|"), manifestDigest: manifest.packagedContextDigest }).receipt; } catch { throw new RetrievalError("AUDIT_UNAVAILABLE"); }
    return { outcome: "completed", chunks: ordered, manifest, auditReceipt: receipt };
  }
  private merge(candidates: readonly Candidate[]): Candidate[] { const merged = new Map<string, Candidate>(); for (const candidate of candidates) { const key = `${candidate.resourceRef}|${candidate.versionRef}|${candidate.chunkRef}`; const existing = merged.get(key); if (!existing || candidate.rank < existing.rank) merged.set(key, candidate); } return [...merged.values()].sort((a, b) => a.rank - b.rank).slice(0, 1000); }
  private score(candidates: readonly Candidate[], chunk: RetrievedChunk): number { return candidates.find((candidate) => candidate.resourceRef === chunk.resourceRef && candidate.chunkRef === chunk.chunkRef)?.rank ?? Number.MAX_SAFE_INTEGER; }
}
