export type TurnState = "INTENT_COMMITTED" | "GENERATING" | "COMPLETED" | "FAILED" | "CANCELLED" | "DEGRADED_OUTPUT";
export type TerminalState = "COMPLETED" | "FAILED" | "CANCELLED";
export class MemoryError extends Error { constructor(readonly code: "AUTHORIZATION_DENIED" | "AUDIT_UNAVAILABLE" | "IDEMPOTENCY_CONFLICT" | "CONVERSATION_CONFLICT" | "TURN_NOT_FOUND" | "TURN_STATE_CONFLICT" | "FENCE_INVALID" | "OUTPUT_EVIDENCE_INVALID" | "REDISCLOSURE_DENIED" | "DURABILITY_ERROR") { super(code); } }
export interface MemoryAuthorization { authorize(input: { requestId: string; subjectRef: string; action: "memory.write" | "memory.read" | "output.redisclosure"; scope: string }): { decisionRef: string }; }
export interface MemoryAudit { admit(input: { event: "turn.begin" | "turn.finalize" | "turn.read" | "output.redisclose" | "turn.repair"; requestId: string; turnId: string; digest: string }): { receipt: string }; }
export interface OutputProofVerifier { verifyBlob(input: { turnId: string; finalizationGeneration: number; outputRef: string; outputHash: string; blobCommitProof: string }): boolean; verifyRunClose(input: { turnId: string; requestId: string; agentRunId: string; closeRef: string; finalRevision: number; counterDigest: string }): boolean; }
export interface MemoryEvidenceGate { verifyFinalization(input: { turnId: string; outputHash: string; manifestRef: string; releaseFenceRef: string; guardEvidenceRefs: readonly string[]; disclosureReservationRef: string }): boolean; commitRedisclosure(input: { requestId: string; turnId: string; subjectRef: string; deviceRef: string; purposeRef: string; outputHash: string; disclosureReservationRef: string; releaseFenceRef: string }): boolean; authorizeRepair(input: { turnId: string; repairFenceRef: string }): boolean; }
export interface Turn { turnId: string; conversationId: string; sequence: number; requestId: string; subjectRef: string; requestDigest: string; userContentRef: string; userContentHash: string; state: TurnState; conversationRevision: number; generationFence: number; outputRef?: string; outputHash?: string; blobCommitProof?: string; agentRunId?: string; agentRunCloseRef?: string; finalizationDigest?: string; }
export interface TurnStatus { turnId: string; conversationId: string; sequence: number; state: TurnState; conversationRevision: number; generationFence: number; }
export interface MemoryOutboxEvent { eventId: string; aggregateId: string; aggregateRevision: number; eventType: "turn.intent_committed" | "turn.finalized" | "turn.degraded"; payloadDigest: string; auditReceipt: string; }
interface Conversation { revision: number; nextSequence: number; }
interface Idempotency { turnId: string; digest: string; subjectRef: string; conversationId: string; }

/** Durable conversation authority. It owns turn state, never authorization or exposure policy. */
export class MemoryAuthority {
  private readonly conversations = new Map<string, Conversation>(); private readonly turns = new Map<string, Turn>(); private readonly idempotency = new Map<string, Idempotency>(); private nextTurn = 0;
  readonly outbox: MemoryOutboxEvent[] = [];
  constructor(private readonly authorization: MemoryAuthorization, private readonly audit: MemoryAudit, private readonly proofs: OutputProofVerifier, private readonly evidence: MemoryEvidenceGate) {}
  begin(input: { requestId: string; subjectRef: string; conversationId: string; userContentRef: string; userContentHash: string; idempotencyKey: string; expectedConversationRevision: number }): Turn {
    const requestDigest = `${input.subjectRef}|${input.conversationId}|${input.userContentRef}|${input.userContentHash}`; const prior = this.idempotency.get(input.idempotencyKey);
    if (prior) { if (prior.digest !== requestDigest || prior.subjectRef !== input.subjectRef || prior.conversationId !== input.conversationId) throw new MemoryError("IDEMPOTENCY_CONFLICT"); return this.copy(this.turns.get(prior.turnId)!); }
    this.authorize(input.requestId, input.subjectRef, "memory.write", `conversation:${input.conversationId}`); const conversation = this.conversations.get(input.conversationId) ?? { revision: 0, nextSequence: 1 };
    if (conversation.revision !== input.expectedConversationRevision) throw new MemoryError("CONVERSATION_CONFLICT"); const turnId = `turn-${++this.nextTurn}`; const receipt = this.admit("turn.begin", input.requestId, turnId, requestDigest); const turn: Turn = { turnId, conversationId: input.conversationId, sequence: conversation.nextSequence, requestId: input.requestId, subjectRef: input.subjectRef, requestDigest, userContentRef: input.userContentRef, userContentHash: input.userContentHash, state: "INTENT_COMMITTED", conversationRevision: conversation.revision + 1, generationFence: 1 };
    this.turns.set(turnId, turn); this.conversations.set(input.conversationId, { revision: conversation.revision + 1, nextSequence: conversation.nextSequence + 1 }); this.idempotency.set(input.idempotencyKey, { turnId, digest: requestDigest, subjectRef: input.subjectRef, conversationId: input.conversationId }); this.outbox.push({ eventId: `memory:${turnId}:intent`, aggregateId: turnId, aggregateRevision: turn.conversationRevision, eventType: "turn.intent_committed", payloadDigest: requestDigest, auditReceipt: receipt }); return this.copy(turn);
  }
  startGeneration(turnId: string, expectedFence: number): Turn { const turn = this.require(turnId); if (turn.state !== "INTENT_COMMITTED" || turn.generationFence !== expectedFence) throw new MemoryError("FENCE_INVALID"); turn.state = "GENERATING"; turn.generationFence += 1; return this.copy(turn); }
  finalize(input: { turnId: string; requestId: string; subjectRef: string; expectedGenerationFence: number; terminal: TerminalState; finalizationGeneration: number; outputRef?: string; outputHash?: string; blobCommitProof?: string; agentRunId?: string; agentRunCloseRef?: string; agentRunFinalRevision?: number; counterDigest?: string; derivedDisclosureManifestRef?: string; releaseFenceRef?: string; guardEvidenceRefs?: readonly string[]; disclosureReservationRef?: string }): Turn {
    const turn = this.require(input.turnId); if (turn.requestId !== input.requestId || turn.subjectRef !== input.subjectRef) throw new MemoryError("FENCE_INVALID"); const digest = JSON.stringify({ ...input, guardEvidenceRefs: input.guardEvidenceRefs ?? [] });
    if (turn.state === "COMPLETED" || turn.state === "FAILED" || turn.state === "CANCELLED") { if (turn.finalizationDigest !== digest) throw new MemoryError("IDEMPOTENCY_CONFLICT"); return this.copy(turn); }
    if (turn.state !== "GENERATING" || turn.generationFence !== input.expectedGenerationFence) throw new MemoryError("FENCE_INVALID"); this.authorize(input.requestId, input.subjectRef, "memory.write", `conversation:${turn.conversationId}`);
    if (input.terminal === "COMPLETED") { if (!input.outputRef || !input.outputHash || !input.blobCommitProof || !input.agentRunId || !input.agentRunCloseRef || input.agentRunFinalRevision === undefined || !input.counterDigest || !input.derivedDisclosureManifestRef || !input.releaseFenceRef || !input.disclosureReservationRef || !input.guardEvidenceRefs?.length || !this.proofs.verifyBlob({ turnId: turn.turnId, finalizationGeneration: input.finalizationGeneration, outputRef: input.outputRef, outputHash: input.outputHash, blobCommitProof: input.blobCommitProof }) || !this.proofs.verifyRunClose({ turnId: turn.turnId, requestId: turn.requestId, agentRunId: input.agentRunId, closeRef: input.agentRunCloseRef, finalRevision: input.agentRunFinalRevision, counterDigest: input.counterDigest }) || !this.evidence.verifyFinalization({ turnId: turn.turnId, outputHash: input.outputHash, manifestRef: input.derivedDisclosureManifestRef, releaseFenceRef: input.releaseFenceRef, guardEvidenceRefs: input.guardEvidenceRefs, disclosureReservationRef: input.disclosureReservationRef })) throw new MemoryError("OUTPUT_EVIDENCE_INVALID"); }
    const receipt = this.admit("turn.finalize", input.requestId, turn.turnId, digest); turn.state = input.terminal; turn.generationFence += 1; turn.finalizationDigest = digest; if (input.terminal === "COMPLETED") Object.assign(turn, { outputRef: input.outputRef, outputHash: input.outputHash, blobCommitProof: input.blobCommitProof, agentRunId: input.agentRunId, agentRunCloseRef: input.agentRunCloseRef }); this.outbox.push({ eventId: `memory:${turn.turnId}:final:${turn.generationFence}`, aggregateId: turn.turnId, aggregateRevision: turn.generationFence, eventType: "turn.finalized", payloadDigest: digest, auditReceipt: receipt }); return this.copy(turn);
  }
  getTurn(input: { requestId: string; subjectRef: string; turnId: string }): TurnStatus { const turn = this.require(input.turnId); this.authorize(input.requestId, input.subjectRef, "memory.read", `conversation:${turn.conversationId}`); this.admit("turn.read", input.requestId, turn.turnId, turn.requestDigest); return { turnId: turn.turnId, conversationId: turn.conversationId, sequence: turn.sequence, state: turn.state, conversationRevision: turn.conversationRevision, generationFence: turn.generationFence }; }
  rediscloseOutput(input: { requestId: string; subjectRef: string; turnId: string; deviceRef: string; purposeRef: string; disclosureReservationRef: string; releaseFenceRef: string }): { outputRef: string; outputHash: string; auditReceipt: string } { const turn = this.require(input.turnId); if (turn.state !== "COMPLETED" || !turn.outputRef || !turn.outputHash) throw new MemoryError("DURABILITY_ERROR"); try { this.authorize(input.requestId, input.subjectRef, "output.redisclosure", `conversation:${turn.conversationId}:${input.deviceRef}:${input.purposeRef}`); } catch { throw new MemoryError("REDISCLOSURE_DENIED"); } if (!this.evidence.commitRedisclosure({ requestId: input.requestId, turnId: turn.turnId, subjectRef: input.subjectRef, deviceRef: input.deviceRef, purposeRef: input.purposeRef, outputHash: turn.outputHash, disclosureReservationRef: input.disclosureReservationRef, releaseFenceRef: input.releaseFenceRef })) throw new MemoryError("REDISCLOSURE_DENIED"); const auditReceipt = this.admit("output.redisclose", input.requestId, turn.turnId, turn.outputHash); return { outputRef: turn.outputRef, outputHash: turn.outputHash, auditReceipt }; }
  repairOutput(input: { turnId: string; proofReadable: boolean; repairFenceRef: string }): Turn { const turn = this.require(input.turnId); if (turn.state === "COMPLETED" && (!input.proofReadable || !turn.outputRef || !turn.outputHash || !turn.blobCommitProof)) { if (!this.evidence.authorizeRepair({ turnId: turn.turnId, repairFenceRef: input.repairFenceRef })) throw new MemoryError("FENCE_INVALID"); const receipt = this.admit("turn.repair", turn.requestId, turn.turnId, turn.outputHash ?? "missing"); turn.state = "DEGRADED_OUTPUT"; turn.generationFence += 1; this.outbox.push({ eventId: `memory:${turn.turnId}:degraded:${turn.generationFence}`, aggregateId: turn.turnId, aggregateRevision: turn.generationFence, eventType: "turn.degraded", payloadDigest: turn.outputHash ?? "missing", auditReceipt: receipt }); } return this.copy(turn); }
  private authorize(requestId: string, subjectRef: string, action: "memory.write" | "memory.read" | "output.redisclosure", scope: string): void { try { this.authorization.authorize({ requestId, subjectRef, action, scope }); } catch { throw new MemoryError("AUTHORIZATION_DENIED"); } }
  private admit(event: "turn.begin" | "turn.finalize" | "turn.read" | "output.redisclose" | "turn.repair", requestId: string, turnId: string, digest: string): string { try { return this.audit.admit({ event, requestId, turnId, digest }).receipt; } catch { throw new MemoryError("AUDIT_UNAVAILABLE"); } }
  private require(turnId: string): Turn { const turn = this.turns.get(turnId); if (!turn) throw new MemoryError("TURN_NOT_FOUND"); return turn; }
  private copy(turn: Turn): Turn { return { ...turn }; }
}
