export type QuarantineReason = "SIZE_LIMIT" | "TYPE_MISMATCH" | "UNSUPPORTED_TYPE" | "MALWARE" | "ACTIVE_CONTENT" | "EXTERNAL_REFERENCE" | "ENCRYPTED_ARCHIVE" | "EXPANSION_LIMIT" | "PARSER_FAILURE" | "ISOLATION_VIOLATION";
export type IntakeStatus = "ACCEPTED" | "QUARANTINED";
export class IntakeError extends Error { constructor(readonly code: "INVALID_PROFILE" | "CONTENT_HASH_MISMATCH" | "QUARANTINED" | "SANDBOX_UNAVAILABLE") { super(code); } }
export interface ParserProfile { digest: string; imageDigest: string; supportedTypes: readonly string[]; maxInputBytes: number; maxExpandedBytes: number; maxExpansionRatio: number; maxArchiveDepth: number; maxArchiveMembers: number; maxPages: number; maxPixels: number; maxObjects: number; maxCpuMs: number; maxMemoryBytes: number; maxFileDescriptors: number; maxWallMs: number; }
export interface IntakeScanner { inspect(input: { inputRef: string; declaredType: string; byteLength: number }): { detectedType: string; malwareDetected: boolean; activeContent: boolean; externalReference: boolean; encryptedArchive: boolean }; }
export interface ContentHasher { verify(input: { inputRef: string; claimedDigest: string; byteLength: number }): boolean; }
export interface ContentSandbox { run(input: { jobId: string; inputRef: string; inputDigest: string; declaredType: string; parserImageDigest: string; extractionProfileDigest: string; limits: Omit<ParserProfile, "digest" | "imageDigest" | "supportedTypes">; isolationClass: "ingestion-parser"; readCapability: "single-object-read-only"; writeCapability: "bounded-write-only"; network: "none"; dns: false; platformIdentity: false; credentials: false }): { outputDigest?: string; detectedType: string; limitHit?: "expanded_bytes" | "expansion_ratio" | "archive_depth" | "archive_members" | "pages" | "pixels" | "objects" | "cpu" | "memory" | "file_descriptors" | "wall_time"; parserCrashed: boolean; isolationEvidenceValid: boolean; microvmDestroyed: boolean; outputValidated: boolean }; }
export interface QuarantineRecord { jobId: string; inputRef: string; inputDigest: string; status: IntakeStatus; reason?: QuarantineReason; detectedType?: string; outputDigest?: string; }

/** Intake boundary for attacker-controlled documents. It never parses content in-process. */
export class UntrustedContentIntake {
  private nextJob = 0; private readonly outcomes = new Map<string, QuarantineRecord>(); readonly quarantine: QuarantineRecord[] = [];
  constructor(private readonly scanner: IntakeScanner, private readonly hasher: ContentHasher, private readonly sandbox: ContentSandbox) {}
  submit(input: { inputRef: string; contentDigest: string; byteLength: number; declaredType: string; profile: ParserProfile }): QuarantineRecord {
    this.validateProfile(input.profile); const prior = this.outcomes.get(input.contentDigest); if (prior) return { ...prior }; const jobId = `content-job-${++this.nextJob}`;
    if (!this.hasher.verify({ inputRef: input.inputRef, claimedDigest: input.contentDigest, byteLength: input.byteLength })) throw new IntakeError("CONTENT_HASH_MISMATCH");
    if (input.byteLength > input.profile.maxInputBytes) return this.reject(jobId, input, "SIZE_LIMIT"); const scan = this.scanner.inspect({ inputRef: input.inputRef, declaredType: input.declaredType, byteLength: input.byteLength });
    if (scan.malwareDetected) return this.reject(jobId, input, "MALWARE", scan.detectedType); if (scan.detectedType !== input.declaredType) return this.reject(jobId, input, "TYPE_MISMATCH", scan.detectedType); if (!input.profile.supportedTypes.includes(scan.detectedType)) return this.reject(jobId, input, "UNSUPPORTED_TYPE", scan.detectedType); if (scan.activeContent) return this.reject(jobId, input, "ACTIVE_CONTENT", scan.detectedType); if (scan.externalReference) return this.reject(jobId, input, "EXTERNAL_REFERENCE", scan.detectedType); if (scan.encryptedArchive) return this.reject(jobId, input, "ENCRYPTED_ARCHIVE", scan.detectedType);
    const { digest: _digest, imageDigest: _imageDigest, supportedTypes: _types, ...limits } = input.profile; let result; try { result = this.sandbox.run({ jobId, inputRef: input.inputRef, inputDigest: input.contentDigest, declaredType: input.declaredType, parserImageDigest: input.profile.imageDigest, extractionProfileDigest: input.profile.digest, limits, isolationClass: "ingestion-parser", readCapability: "single-object-read-only", writeCapability: "bounded-write-only", network: "none", dns: false, platformIdentity: false, credentials: false }); } catch { throw new IntakeError("SANDBOX_UNAVAILABLE"); }
    if (!result.isolationEvidenceValid || !result.microvmDestroyed) return this.reject(jobId, input, "ISOLATION_VIOLATION", result.detectedType); if (result.limitHit) return this.reject(jobId, input, "EXPANSION_LIMIT", result.detectedType); if (result.parserCrashed || !result.outputValidated || !result.outputDigest || result.detectedType !== scan.detectedType) return this.reject(jobId, input, "PARSER_FAILURE", result.detectedType);
    const accepted = { jobId, inputRef: input.inputRef, inputDigest: input.contentDigest, status: "ACCEPTED" as const, detectedType: result.detectedType, outputDigest: result.outputDigest }; this.outcomes.set(input.contentDigest, accepted); return { ...accepted };
  }
  private reject(jobId: string, input: { inputRef: string; contentDigest: string }, reason: QuarantineReason, detectedType?: string): QuarantineRecord { const record = { jobId, inputRef: input.inputRef, inputDigest: input.contentDigest, status: "QUARANTINED" as const, reason, detectedType }; this.quarantine.push(record); this.outcomes.set(input.contentDigest, record); return { ...record }; }
  private validateProfile(profile: ParserProfile): void { const values = [profile.maxInputBytes, profile.maxExpandedBytes, profile.maxExpansionRatio, profile.maxArchiveDepth, profile.maxArchiveMembers, profile.maxPages, profile.maxPixels, profile.maxObjects, profile.maxCpuMs, profile.maxMemoryBytes, profile.maxFileDescriptors, profile.maxWallMs]; if (!/^sha256:[a-zA-Z0-9._-]+$/.test(profile.digest) || !/^sha256:[a-zA-Z0-9._-]+$/.test(profile.imageDigest) || profile.supportedTypes.length === 0 || values.some((value) => !Number.isSafeInteger(value) || value <= 0) || profile.maxExpandedBytes < profile.maxInputBytes) throw new IntakeError("INVALID_PROFILE"); }
}
