export type EmployeeTurnState = "submitting" | "accepted" | "authorizing" | "retrieving" | "queued" | "generating_internal" | "finalizing" | "completed" | "denied" | "degraded" | "cancelled" | "failed_retryable" | "failed_terminal" | "authorization_changed";
export interface ReleaseEnvelope { schemaVersion: 1; turnId: string; outputDigest: `sha256:${string}`; expiresAt: number; }
export interface Citation { resourceRef: string; versionRef: string; chunkRef: string; anchor: string; }
export type EmployeeTurnPresentation = { label: string; showOutput: boolean; allowStop: boolean; allowRetry: boolean; hideContent: boolean };

export function presentTurn(state: EmployeeTurnState): EmployeeTurnPresentation {
  const values: Record<EmployeeTurnState, EmployeeTurnPresentation> = {
    submitting: { label: "Sending", showOutput: false, allowStop: true, allowRetry: false, hideContent: false }, accepted: { label: "Request received", showOutput: false, allowStop: true, allowRetry: false, hideContent: false }, authorizing: { label: "Checking access", showOutput: false, allowStop: true, allowRetry: false, hideContent: false }, retrieving: { label: "Finding approved sources", showOutput: false, allowStop: true, allowRetry: false, hideContent: false }, queued: { label: "Waiting for capacity", showOutput: false, allowStop: true, allowRetry: false, hideContent: false }, generating_internal: { label: "Generating securely", showOutput: false, allowStop: true, allowRetry: false, hideContent: false }, finalizing: { label: "Verifying and saving answer", showOutput: false, allowStop: false, allowRetry: false, hideContent: false }, completed: { label: "Completed", showOutput: true, allowStop: false, allowRetry: false, hideContent: false }, denied: { label: "Cannot complete this request", showOutput: false, allowStop: false, allowRetry: false, hideContent: false }, degraded: { label: "Completed with limited context", showOutput: true, allowStop: false, allowRetry: false, hideContent: false }, cancelled: { label: "Stopped", showOutput: false, allowStop: false, allowRetry: false, hideContent: false }, failed_retryable: { label: "Could not complete. Retry when ready.", showOutput: false, allowStop: false, allowRetry: true, hideContent: false }, failed_terminal: { label: "Could not complete this request", showOutput: false, allowStop: false, allowRetry: false, hideContent: false }, authorization_changed: { label: "Access changed. Content is no longer available.", showOutput: false, allowStop: false, allowRetry: false, hideContent: true },
  };
  return values[state];
}
export function verifyRelease(envelope: ReleaseEnvelope, turnId: string, outputDigest: string, now: number): boolean { return envelope.schemaVersion === 1 && envelope.turnId === turnId && envelope.outputDigest === outputDigest && envelope.expiresAt > now; }
export function canResolveCitation(state: EmployeeTurnState, citation: Citation | undefined): citation is Citation { return (state === "completed" || state === "degraded") && citation !== undefined; }
