export type RunState = "OPEN" | "FROZEN" | "EXHAUSTED" | "COMPLETED" | "CANCELLED" | "EXPIRED";
export type StepState = "RESERVED" | "STARTED" | "SUCCEEDED" | "FAILED" | "OUTCOME_UNKNOWN" | "CANCELLED";
export class AgentError extends Error { constructor(readonly code: "CATALOG_INVALID" | "RUN_NOT_FOUND" | "RUN_NOT_OPEN" | "REVISION_CONFLICT" | "ENVELOPE_EXHAUSTED" | "FENCE_INVALID" | "INTENT_CONFLICT" | "APPROVAL_INVALID" | "CLOSE_BLOCKED") { super(code); } }
export interface ToolCatalogEntry { toolId: string; version: string; targetProfileDigest: string; risk: "read" | "reversible_write" | "high_risk"; requiresApproval: boolean; idempotentReplay: boolean; schemaDigest: string; dataFlowProfileDigest: string; }
export interface Envelope { maxSteps: number; maxSideEffects: number; maxCostUnits: number; deadlineAt: number; workflowProfileDigest: string; budgetDecisionRef: string; }
export interface AgentRun { runId: string; requestId: string; subjectRef: string; deviceRef: string; applicationRef: string; state: RunState; revision: number; envelope: Envelope; consumedSteps: number; consumedSideEffects: number; reservedCostUnits: number; }
export interface StepFence { fenceId: string; runId: string; stepId: string; revision: number; intentDigest: string; declaredCostUnits: number; expiresAt: number; nonce: string; }
export interface Approval { approvalId: string; runId: string; stepId: string; intentDigest: string; actorRef: string; approverRef: string; policyEpoch: number; expiresAt: number; used: boolean; }
export interface RunAdmission { authorize(input: { requestId: string; subjectRef: string; deviceRef: string; applicationRef: string; workflowProfileDigest: string; budgetDecisionRef: string }): boolean; }

/** Durable aggregate envelope and canonical catalog; never routes or executes a tool. */
export class AgentRuntime {
  private readonly catalog = new Map<string, ToolCatalogEntry>(); private readonly runs = new Map<string, AgentRun>(); private readonly steps = new Map<string, { fence: StepFence; state: StepState; requiresApproval: boolean; approval?: Approval; consumerAttemptId?: string; startReceipt?: string }>(); private nextRun = 0; private nextFence = 0; private nextApproval = 0;
  readonly outbox: { event: string; runId: string; revision: number; digest: string }[] = [];
  constructor(private readonly admission: RunAdmission, private readonly now = () => Date.now()) {}
  registerTool(entry: ToolCatalogEntry): void { const key = this.toolKey(entry.toolId, entry.version); if (this.catalog.has(key) || !entry.toolId || !entry.version || !this.digest(entry.targetProfileDigest) || !this.digest(entry.schemaDigest) || !this.digest(entry.dataFlowProfileDigest)) throw new AgentError("CATALOG_INVALID"); this.catalog.set(key, Object.freeze({ ...entry })); }
  begin(input: { requestId: string; subjectRef: string; deviceRef: string; applicationRef: string; envelope: Envelope }): AgentRun { if (!input.requestId || !input.subjectRef || !input.deviceRef || !input.applicationRef || input.envelope.deadlineAt <= this.now() || input.envelope.maxSteps <= 0 || input.envelope.maxSideEffects < 0 || input.envelope.maxCostUnits < 0 || !this.digest(input.envelope.workflowProfileDigest) || !input.envelope.budgetDecisionRef || !this.admission.authorize({ requestId: input.requestId, subjectRef: input.subjectRef, deviceRef: input.deviceRef, applicationRef: input.applicationRef, workflowProfileDigest: input.envelope.workflowProfileDigest, budgetDecisionRef: input.envelope.budgetDecisionRef })) throw new AgentError("CATALOG_INVALID"); const run: AgentRun = { runId: `run-${++this.nextRun}`, requestId: input.requestId, subjectRef: input.subjectRef, deviceRef: input.deviceRef, applicationRef: input.applicationRef, state: "OPEN", revision: 1, envelope: { ...input.envelope }, consumedSteps: 0, consumedSideEffects: 0, reservedCostUnits: 0 }; this.runs.set(run.runId, run); this.event("run.begun", run, input.envelope.workflowProfileDigest); return this.copyRun(run); }
  reserveStep(input: { runId: string; expectedRevision: number; stepId: string; toolId: string; toolVersion: string; intentDigest: string; declaredCostUnits: number }): StepFence { const run = this.requireRun(input.runId); const catalog = this.catalog.get(this.toolKey(input.toolId, input.toolVersion)); if (!catalog) throw new AgentError("CATALOG_INVALID"); const key = `${run.runId}:${input.stepId}`; const prior = this.steps.get(key); if (prior) { if (prior.fence.intentDigest !== input.intentDigest || prior.fence.declaredCostUnits !== input.declaredCostUnits) throw new AgentError("INTENT_CONFLICT"); return { ...prior.fence }; } this.assertOpen(run, input.expectedRevision); if (input.declaredCostUnits < 0 || run.consumedSteps + 1 > run.envelope.maxSteps || run.reservedCostUnits + input.declaredCostUnits > run.envelope.maxCostUnits || (catalog.risk !== "read" && run.consumedSideEffects + 1 > run.envelope.maxSideEffects)) { run.state = "EXHAUSTED"; throw new AgentError("ENVELOPE_EXHAUSTED"); } run.consumedSteps += 1; run.reservedCostUnits += input.declaredCostUnits; if (catalog.risk !== "read") run.consumedSideEffects += 1; run.revision += 1; const fence: StepFence = { fenceId: `step-fence-${++this.nextFence}`, runId: run.runId, stepId: input.stepId, revision: run.revision, intentDigest: input.intentDigest, declaredCostUnits: input.declaredCostUnits, expiresAt: run.envelope.deadlineAt, nonce: `nonce-${this.nextFence}` }; this.steps.set(key, { fence, state: "RESERVED", requiresApproval: catalog.requiresApproval }); this.event("step.reserved", run, input.intentDigest); return { ...fence }; }
  approve(input: { runId: string; stepId: string; actorRef: string; approverRef: string; intentDigest: string; policyEpoch: number; expiresAt: number }): Approval { const step = this.requireStep(input.runId, input.stepId); if (input.actorRef === input.approverRef || step.fence.intentDigest !== input.intentDigest || input.expiresAt <= this.now() || step.approval) throw new AgentError("APPROVAL_INVALID"); const approval = { approvalId: `approval-${++this.nextApproval}`, runId: input.runId, stepId: input.stepId, intentDigest: input.intentDigest, actorRef: input.actorRef, approverRef: input.approverRef, policyEpoch: input.policyEpoch, expiresAt: input.expiresAt, used: false }; step.approval = approval; return { ...approval }; }
  start(input: { fence: StepFence; consumerAttemptId: string; exactIntentDigest: string; policyEpoch: number; approvalId?: string }): string { const run = this.requireRun(input.fence.runId); const step = this.requireStep(input.fence.runId, input.fence.stepId); if (step.state === "STARTED") { if (step.consumerAttemptId === input.consumerAttemptId && step.fence.intentDigest === input.exactIntentDigest) return step.startReceipt!; throw new AgentError("FENCE_INVALID"); } if (run.state !== "OPEN" || step.state !== "RESERVED" || step.fence.fenceId !== input.fence.fenceId || step.fence.nonce !== input.fence.nonce || step.fence.expiresAt <= this.now() || input.exactIntentDigest !== step.fence.intentDigest || !input.consumerAttemptId) throw new AgentError("FENCE_INVALID"); if ((step.requiresApproval && !step.approval) || (step.approval && (!input.approvalId || input.approvalId !== step.approval.approvalId || step.approval.used || step.approval.expiresAt <= this.now() || step.approval.policyEpoch !== input.policyEpoch))) throw new AgentError("APPROVAL_INVALID"); if (step.approval) step.approval.used = true; step.state = "STARTED"; step.consumerAttemptId = input.consumerAttemptId; step.startReceipt = `start:${run.runId}:${step.fence.stepId}:${run.revision + 1}`; run.revision += 1; this.event("step.started", run, step.fence.intentDigest); return step.startReceipt; }
  finalize(input: { runId: string; stepId: string; state: Extract<StepState, "SUCCEEDED" | "FAILED" | "OUTCOME_UNKNOWN" | "CANCELLED"> }): AgentRun { const run = this.requireRun(input.runId); const step = this.requireStep(input.runId, input.stepId); if (step.state !== "STARTED") throw new AgentError("FENCE_INVALID"); step.state = input.state; run.revision += 1; this.event("step.finalized", run, step.fence.intentDigest); return this.copyRun(run); }
  close(runId: string, expectedRevision: number, terminal: Extract<RunState, "COMPLETED" | "CANCELLED" | "EXPIRED">): { run: AgentRun; closeReceipt: string } { const run = this.requireRun(runId); if (run.revision !== expectedRevision || run.state !== "OPEN") throw new AgentError("REVISION_CONFLICT"); if (terminal === "COMPLETED" && [...this.steps.entries()].some(([key, step]) => key.startsWith(`${runId}:`) && (step.state === "RESERVED" || step.state === "STARTED" || step.state === "OUTCOME_UNKNOWN"))) throw new AgentError("CLOSE_BLOCKED"); run.state = terminal; run.revision += 1; const receipt = `close:${run.runId}:${run.revision}:${run.consumedSteps}:${run.reservedCostUnits}`; this.event("run.closed", run, receipt); return { run: this.copyRun(run), closeReceipt: receipt }; }
  private assertOpen(run: AgentRun, expectedRevision: number): void { if (run.state !== "OPEN" || run.envelope.deadlineAt <= this.now()) { if (run.envelope.deadlineAt <= this.now()) run.state = "EXPIRED"; throw new AgentError("RUN_NOT_OPEN"); } if (run.revision !== expectedRevision) throw new AgentError("REVISION_CONFLICT"); }
  private requireRun(runId: string): AgentRun { const run = this.runs.get(runId); if (!run) throw new AgentError("RUN_NOT_FOUND"); return run; } private requireStep(runId: string, stepId: string) { const step = this.steps.get(`${runId}:${stepId}`); if (!step) throw new AgentError("FENCE_INVALID"); return step; } private event(event: string, run: AgentRun, digest: string): void { this.outbox.push({ event, runId: run.runId, revision: run.revision, digest }); } private toolKey(toolId: string, version: string): string { return `${toolId}:${version}`; } private digest(value: string): boolean { return /^sha256:[A-Za-z0-9._-]+$/.test(value); } private copyRun(run: AgentRun): AgentRun { return { ...run, envelope: { ...run.envelope } }; }
}
