export type ModelState = "REGISTERED" | "APPROVED" | "ROUTABLE" | "REVOKED";
export class RegistryError extends Error { constructor(readonly code: "INVALID_ARTIFACT" | "VERSION_EXISTS" | "NOT_FOUND" | "EVIDENCE_INSUFFICIENT" | "NOT_ROUTABLE" | "REVOKED" | "ROLLOUT_INVALID" | "AUDIT_UNAVAILABLE") { super(code); } }
export interface CapabilityProfile { digest: string; contextWindow: number; supportsToolCalling: boolean; supportsVision: boolean; supportsEmbeddings: boolean; runtimeFamily: string; quantization: string; measuredThroughputEvidenceRef: string; approvedRequestClasses: readonly string[]; }
export interface ModelVersion { modelId: string; version: string; artifactRef: string; artifactDigest: string; manifestDigest: string; provenanceRef: string; sbomRef: string; modelCardRef: string; signerRef: string; state: ModelState; capability?: CapabilityProfile; evidenceRefs: readonly string[]; }
export interface Evidence { evidenceRef: string; artifactDigest: string; kind: "evaluation" | "red_team" | "privacy" | "provenance" | "security"; signed: boolean; passed: boolean; criticalFailure: boolean; deploymentProfileDigest: string; }
export interface RegistryAudit { admit(input: { event: "model.approved" | "model.promoted" | "model.revoked" | "alias.updated" | "rollout.activated"; digest: string }): { receipt: string }; }
export interface SnapshotSigner { sign(snapshot: Omit<EligibilitySnapshot, "signature">): string; }
export interface EvidenceVerifier { verify(evidence: Evidence): boolean; }
export interface PrivilegedChangeGate { verify(input: { operation: "approve" | "promote" | "revoke" | "alias" | "rollout"; targetDigest: string; changeFenceRef: string }): boolean; }
export interface EligibilitySnapshot { issuedAt: number; expiresAt: number; registryEpoch: number; emergencyDenyEpoch: number; routable: readonly { artifactDigest: string; capabilityDigest: string }[]; signature: string; }
export interface RolloutPolicy { rolloutId: string; revision: number; capabilityDigest: string; members: readonly { artifactDigest: string; weight: number }[]; assignmentKey: string; evidenceDigest: string; }

/** Promotion/eligibility authority. It never routes requests or exposes artifact bytes. */
export class ModelRegistry {
  private readonly versions = new Map<string, ModelVersion>(); private readonly evidence = new Map<string, Evidence[]>(); private readonly aliases = new Map<string, string>(); private readonly policies = new Map<string, RolloutPolicy>(); private registryEpoch = 0; private denyEpoch = 0;
  readonly outbox: { event: "model.eligibility.changed" | "model.revoked" | "rollout.changed"; digest: string; epoch: number; auditReceipt: string }[] = [];
  constructor(private readonly audit: RegistryAudit, private readonly signer: SnapshotSigner, private readonly evidenceVerifier: EvidenceVerifier, private readonly changeGate: PrivilegedChangeGate, private readonly now = () => Date.now()) {}
  register(input: Omit<ModelVersion, "state" | "evidenceRefs" | "capability">): ModelVersion { const key = this.key(input.modelId, input.version); if (this.versions.has(key)) throw new RegistryError("VERSION_EXISTS"); if (!input.artifactRef.startsWith("oci://internal/") || !this.digest(input.artifactDigest) || !this.digest(input.manifestDigest) || !input.provenanceRef || !input.sbomRef || !input.modelCardRef || !input.signerRef) throw new RegistryError("INVALID_ARTIFACT"); const version: ModelVersion = { ...input, state: "REGISTERED", evidenceRefs: [] }; this.versions.set(key, version); return this.copy(version); }
  attachCapability(modelId: string, version: string, capability: CapabilityProfile): void { const target = this.require(modelId, version); if (target.state !== "REGISTERED" || !this.digest(capability.digest) || capability.contextWindow <= 0 || !capability.runtimeFamily || !capability.quantization || !capability.measuredThroughputEvidenceRef || capability.approvedRequestClasses.length === 0) throw new RegistryError("INVALID_ARTIFACT"); target.capability = { ...capability, approvedRequestClasses: [...capability.approvedRequestClasses] }; }
  ingestEvidence(value: Evidence): void { if (!this.digest(value.artifactDigest) || !value.evidenceRef || !value.deploymentProfileDigest || !value.signed || !this.evidenceVerifier.verify(value) || ![...this.versions.values()].some((version) => version.artifactDigest === value.artifactDigest)) throw new RegistryError("INVALID_ARTIFACT"); const evidence = this.evidence.get(value.artifactDigest) ?? []; if (evidence.some((entry) => entry.evidenceRef === value.evidenceRef)) return; evidence.push({ ...value }); this.evidence.set(value.artifactDigest, evidence); }
  approve(modelId: string, version: string, expectedDeploymentProfileDigest: string, changeFenceRef: string): ModelVersion { const target = this.require(modelId, version); if (!this.changeGate.verify({ operation: "approve", targetDigest: target.artifactDigest, changeFenceRef })) throw new RegistryError("EVIDENCE_INSUFFICIENT"); if (target.state === "REVOKED") throw new RegistryError("REVOKED"); const evidence = this.evidence.get(target.artifactDigest) ?? []; const required = ["evaluation", "red_team", "privacy", "provenance", "security"] as const; if (!target.capability || required.some((kind) => !evidence.some((entry) => entry.kind === kind && entry.signed && entry.passed && entry.deploymentProfileDigest === expectedDeploymentProfileDigest)) || evidence.some((entry) => entry.criticalFailure)) throw new RegistryError("EVIDENCE_INSUFFICIENT"); const receipt = this.admit("model.approved", target.artifactDigest); target.state = "APPROVED"; target.evidenceRefs = evidence.map((entry) => entry.evidenceRef); this.registryEpoch += 1; this.outbox.push({ event: "model.eligibility.changed", digest: target.artifactDigest, epoch: this.registryEpoch, auditReceipt: receipt }); return this.copy(target); }
  promote(modelId: string, version: string, expectedDeploymentProfileDigest: string, changeFenceRef: string): ModelVersion { const target = this.require(modelId, version); const evidence = this.evidence.get(target.artifactDigest) ?? []; const required = ["evaluation", "red_team", "privacy", "provenance", "security"] as const; if (!this.changeGate.verify({ operation: "promote", targetDigest: target.artifactDigest, changeFenceRef })) throw new RegistryError("EVIDENCE_INSUFFICIENT"); if (target.state === "REVOKED") throw new RegistryError("REVOKED"); if (target.state !== "APPROVED" || required.some((kind) => !evidence.some((entry) => entry.kind === kind && entry.signed && entry.passed && entry.deploymentProfileDigest === expectedDeploymentProfileDigest)) || evidence.some((entry) => entry.criticalFailure)) throw new RegistryError("EVIDENCE_INSUFFICIENT"); const receipt = this.admit("model.promoted", target.artifactDigest); target.state = "ROUTABLE"; this.registryEpoch += 1; this.outbox.push({ event: "model.eligibility.changed", digest: target.artifactDigest, epoch: this.registryEpoch, auditReceipt: receipt }); return this.copy(target); }
  revoke(modelId: string, version: string, changeFenceRef: string): void { const target = this.require(modelId, version); if (!this.changeGate.verify({ operation: "revoke", targetDigest: target.artifactDigest, changeFenceRef })) throw new RegistryError("EVIDENCE_INSUFFICIENT"); const receipt = this.admit("model.revoked", target.artifactDigest); target.state = "REVOKED"; this.registryEpoch += 1; this.denyEpoch += 1; this.outbox.push({ event: "model.revoked", digest: target.artifactDigest, epoch: this.denyEpoch, auditReceipt: receipt }); }
  setAlias(modelId: string, alias: string, version: string, changeFenceRef: string): void { const target = this.require(modelId, version); if (!this.changeGate.verify({ operation: "alias", targetDigest: target.artifactDigest, changeFenceRef })) throw new RegistryError("EVIDENCE_INSUFFICIENT"); if (target.state !== "ROUTABLE") throw new RegistryError("NOT_ROUTABLE"); const receipt = this.admit("alias.updated", `${modelId}:${alias}:${target.artifactDigest}`); this.aliases.set(`${modelId}:${alias}`, target.artifactDigest); this.registryEpoch += 1; this.outbox.push({ event: "model.eligibility.changed", digest: target.artifactDigest, epoch: this.registryEpoch, auditReceipt: receipt }); }
  activateRollout(policy: RolloutPolicy, changeFenceRef: string): void { const prior = this.policies.get(policy.rolloutId); if (!this.changeGate.verify({ operation: "rollout", targetDigest: policy.evidenceDigest, changeFenceRef }) || !policy.rolloutId || !Number.isSafeInteger(policy.revision) || policy.revision <= (prior?.revision ?? 0) || !this.digest(policy.capabilityDigest) || !policy.assignmentKey || !this.digest(policy.evidenceDigest) || policy.members.length === 0 || policy.members.some((member) => !this.digest(member.artifactDigest) || !Number.isSafeInteger(member.weight) || member.weight < 0) || policy.members.reduce((sum, member) => sum + member.weight, 0) !== 10_000 || policy.members.some((member, index) => policy.members.findIndex((other) => other.artifactDigest === member.artifactDigest) !== index) || policy.members.some((member) => ![...this.versions.values()].some((version) => version.artifactDigest === member.artifactDigest && version.state === "ROUTABLE" && version.capability?.digest === policy.capabilityDigest))) throw new RegistryError("ROLLOUT_INVALID"); const receipt = this.admit("rollout.activated", `${policy.rolloutId}:${policy.revision}:${policy.evidenceDigest}`); this.policies.set(policy.rolloutId, { ...policy, members: policy.members.map((member) => ({ ...member })) }); this.registryEpoch += 1; this.outbox.push({ event: "rollout.changed", digest: policy.evidenceDigest, epoch: this.registryEpoch, auditReceipt: receipt }); }
  snapshot(maxAgeMs: number): EligibilitySnapshot { if (!Number.isSafeInteger(maxAgeMs) || maxAgeMs <= 0) throw new RegistryError("INVALID_ARTIFACT"); const unsigned = { issuedAt: this.now(), expiresAt: this.now() + maxAgeMs, registryEpoch: this.registryEpoch, emergencyDenyEpoch: this.denyEpoch, routable: [...this.versions.values()].filter((version) => version.state === "ROUTABLE" && version.capability).map((version) => ({ artifactDigest: version.artifactDigest, capabilityDigest: version.capability!.digest })) }; return { ...unsigned, signature: this.signer.sign(unsigned) }; }
  private admit(event: "model.approved" | "model.promoted" | "model.revoked" | "alias.updated" | "rollout.activated", digest: string): string { try { return this.audit.admit({ event, digest }).receipt; } catch { throw new RegistryError("AUDIT_UNAVAILABLE"); } }
  private require(modelId: string, version: string): ModelVersion { const value = this.versions.get(this.key(modelId, version)); if (!value) throw new RegistryError("NOT_FOUND"); return value; }
  private key(modelId: string, version: string): string { return `${modelId}:${version}`; } private digest(value: string): value is `sha256:${string}` { return /^sha256:[A-Za-z0-9._-]+$/.test(value); } private copy(value: ModelVersion): ModelVersion { return { ...value, evidenceRefs: [...value.evidenceRefs], capability: value.capability ? { ...value.capability, approvedRequestClasses: [...value.capability.approvedRequestClasses] } : undefined }; }
}
