/* Generated by scripts/contracts/rag-generate.mjs from contracts/rag/*.v1.schema.json. Do not edit directly. */
export const RAG_CONTRACT_VERSION = "1.0.0" as const;
export const SCHEMA_DIGESTS = {
    "authorization-manifest.v1.schema.json": "3ce2592a9542616cb4fccc3fb421ac5b9ce4ae5b6d2355fa7fe12132ffed02d8",
    "error.v1.schema.json": "be45bdc004ed47d4361c389169bbbba7d43faf21e655989634176133b8e7bec1",
    "request.v1.schema.json": "1fdfd8d2f1ded75d79fac0b8847c213fd48495b9f9da0505b60bb4faa812c64a",
    "retrieval-request.v1.schema.json": "da285d32ab68fa442f0cee5555dd2712c425a6cc49e5c354e2bf27722252b80a",
    "retrieval-result.v1.schema.json": "c0b4387cd8a38ed973ab7efa2dda77bc338b988d2025eec2d3b51895b7353fe2",
    "retrieved-context.v1.schema.json": "3862455bf881c958d2239f892887c70a1d7f6793b8377d5d130fe85ceb1be037",
    "retrieved-source.v1.schema.json": "bd31df7ec7c655e1d916fe87c3f58d25c71b401bb9149dcfc7b7da3b31b2cf02",
  };

export type RetrievalStatus = "context" | "no_context" | "denied_policy" | "failed_downstream";
export type RetrievalMode = "lexical" | "semantic" | "graph" | "hybrid" | "structured" | "citation_refresh";
export type ClassificationRef = "public" | "internal" | "confidential" | "restricted";
export type RagErrorCode = "INVALID_ARGUMENT" | "UNAUTHENTICATED" | "FORBIDDEN" | "STALE_AUTHORITY" | "RATE_LIMITED" | "OVERLOADED" | "DEPENDENCY_UNAVAILABLE" | "DEADLINE_EXCEEDED" | "CANCELLED" | "NOT_FOUND_OR_NOT_DISCLOSABLE" | "QUARANTINED";

export interface RagRequest {
  request_id: string;
  turn_id: string;
  subject_ref: string;
  session_ref: string;
  device_ref: string;
  application_id: "lens-employee-client";
  purpose_ref: string;
  retrieval_class: "enterprise-grounded";
  query_digest: `sha256:${string}`;
  deadline_at: number;
  cancellation: boolean;
  retry_budget: number;
  bulkhead: "interactive" | "management";
  capability: string;
}

export interface RetrievalRequest {
  request_id: string;
  turn_id: string;
  caller_workload_ref: "ai-orchestrator";
  subject_ref: string;
  session_ref: string;
  device_ref: string;
  application_id: "lens-employee-client";
  query_digest: `sha256:${string}`;
  query_text: string;
  purpose_ref: string;
  retrieval_class: "enterprise-grounded";
  corpus_ref: string;
  mode: RetrievalMode;
  candidate_limit: number;
  deadline_at: number;
  cancellation: boolean;
  bulkhead: "interactive" | "management";
  visibility_minimum: number;
}

export interface RetrievedSource {
  document_version_ref: string;
  chunk_ref: string;
  content_digest: `sha256:${string}`;
  citation_anchor: string;
  classification_ref: ClassificationRef;
}

export interface RetrievedContext extends RetrievedSource {
  text: string;
}

export interface AuthorizationManifest {
  digest: `sha256:${string}`;
  retrieved_at: number;
  source_revision_digest: `sha256:${string}`;
  operation_decision_ref: string;
  candidate_decision_ref: string;
  policy_revision: number;
  subject_security_revision: number;
  resource_security_revision_digest: `sha256:${string}`;
  expires_at: number;
  sources: readonly RetrievedSource[];
}

export type RetrievalResult =
  | { status: "context"; retrieval_id: string; request_id: string; turn_id: string; visibility_sequence: number; index_generation: string; context_digest: `sha256:${string}`; manifest: AuthorizationManifest; sources: readonly RetrievedContext[] }
  | { status: "no_context" }
  | { status: "denied_policy" }
  | { status: "failed_downstream" };

export interface RagError {
  error: "RAG_REQUEST_FAILED";
  code: RagErrorCode;
  message: string;
  retryable: boolean;
  retry_after_ms?: number;
  correlation_id: string;
}
