import type { ComponentProps } from "react";
import {
  IconAccessible as Accessibility,
  IconActivity as Activity,
  IconAlertCircle as AlertCircle,
  IconAlertTriangle as AlertTriangle,
  IconArrowDown as ArrowDown,
  IconArrowDownToArc as ArrowDownToLine,
  IconArrowLeft as ArrowLeft,
  IconArrowsLeftRight as ArrowLeftRight,
  IconArrowRight as ArrowRight,
  IconArrowUp as ArrowUp,
  IconArrowBarToUp as ArrowUpFromLine,
  IconBell as Bell,
  IconBook as BookOpen,
  IconRobot as Bot,
  IconBox as Box,
  IconBoxMultiple as Boxes,
  IconBraces as Braces,
  IconBrain as Brain,
  IconBug as Bug,
  IconLetterCase as CaseSensitive,
  IconCheck as Check,
  IconCheck as CheckIcon,
  IconCircleCheck as CheckCircle2,
  IconChevronDown as ChevronDown,
  IconChevronDown as ChevronDownIcon,
  IconChevronRight as ChevronRight,
  IconChevronRight as ChevronRightIcon,
  IconChevronUp as ChevronUp,
  IconChevronUp as ChevronUpIcon,
  IconCircle as Circle,
  IconCircleDashed as CircleDashed,
  IconHelpCircle as CircleHelp,
  IconClipboardList as ClipboardList,
  IconClipboardText as ClipboardPaste,
  IconClock as Clock,
  IconCloud as Cloud,
  IconCloudDown as CloudDownload,
  IconCloudUp as CloudUpload,
  IconCode as Code2,
  IconCoin as Coins,
  IconColumns2 as Columns2,
  IconCommand as Command,
  IconComponents as Component,
  IconCopy as Copy,
  IconCrosshair as Crosshair,
  IconDatabase as Database,
  IconFileDiff as Diff,
  IconEraser as Eraser,
  IconExternalLink as ExternalLink,
  IconEye as Eye,
  IconFileCode as FileCode,
  IconFileCode2 as FileCode2,
  IconFileDiff as FileDiff,
  IconJson as FileJson,
  IconFileMinus as FileMinus,
  IconFilePencil as FilePenLine,
  IconFilePlus as FilePlus,
  IconFilePlus as FilePlus2,
  IconFileText as FileText,
  IconFileAlert as FileWarning,
  IconFolder as Folder,
  IconFolderCode as FolderGit2,
  IconFolderCog as FolderKanban,
  IconFolderOpen as FolderOpen,
  IconFolderPlus as FolderPlus,
  IconFolderSearch as FolderSearch,
  IconSitemap as FolderTree,
  IconFunction as FunctionSquare,
  IconGauge as Gauge,
  IconGitBranch as GitBranch,
  IconGitCommit as GitCommitHorizontal,
  IconGitCompare as GitCompareArrows,
  IconGitBranch as GitGraph,
  IconGitMerge as GitMerge,
  IconGitPullRequest as GitPullRequest,
  IconWorld as Globe,
  IconGripVertical as GripVertical,
  IconHandStop as Hand,
  IconHash as Hash,
  IconHelpCircle as HelpCircle,
  IconHistory as History,
  IconHome as Home,
  IconPhoto as Image,
  IconInfoCircle as Info,
  IconKeyboard as Keyboard,
  IconLayersIntersect as Layers,
  IconLayout as Layout,
  IconLayoutGrid as LayoutGrid,
  IconLayoutSidebarLeftCollapse as LayoutPanelLeft,
  IconLayoutSidebarLeftExpand as PanelLeftExpand,
  IconTemplate as LayoutTemplate,
  IconLifebuoy as LifeBuoy,
  IconChartLine as LineChart,
  IconLoader2 as Loader2,
  IconLock as Lock,
  IconLogin as LogIn,
  IconLogout as LogOut,
  IconMaximize as Maximize2,
  IconMenu2 as Menu,
  IconMessage as MessageSquare,
  IconMessagePlus as MessageSquarePlus,
  IconMinimize as Minimize2,
  IconMinus as Minus,
  IconDeviceDesktop as Monitor,
  IconMoon as Moon,
  IconDots as MoreHorizontal,
  IconDots as MoreHorizontalIcon,
  IconPointer as MousePointer2,
  IconPointerBolt as MousePointerClick,
  IconPalette as Palette,
  IconLayoutBottombar as PanelBottom,
  IconLayoutBottombarCollapse as PanelBottomClose,
  IconLayoutSidebar as PanelLeft,
  IconLayoutSidebarLeftCollapse as PanelLeftClose,
  IconLayoutSidebarRight as PanelRight,
  IconLayoutSidebarRightCollapse as PanelRightCollapse,
  IconLayoutSidebarRightExpand as PanelRightExpand,
  IconPaperclip as Paperclip,
  IconPencil as Pencil,
  IconPin as Pin,
  IconPinnedOff as PinOff,
  IconPlayerPlay as Play,
  IconPlug as Plug,
  IconPlus as Plus,
  IconRadio as Radio,
  IconArrowBackUp as Redo2,
  IconRefresh as RefreshCw,
  IconRegex as Regex,
  IconReplace as Replace,
  IconRocket as Rocket,
  IconRotateClockwise as RotateCcw,
  IconLayoutRows as Rows2,
  IconDeviceFloppy as Save,
  IconScissors as Scissors,
  IconScript as ScrollText,
  IconSearch as Search,
  IconSettings as Settings,
  IconSettings2 as Settings2,
  IconShield as Shield,
  IconShieldExclamation as ShieldAlert,
  IconShieldCheck as ShieldCheck,
  IconSkull as Skull,
  IconAdjustmentsHorizontal as SlidersHorizontal,
  IconSparkles as Sparkles,
  IconSquare as Square,
  IconExternalLink as SquareArrowOutUpRight,
  IconStack2 as SquareStack,
  IconTerminal as SquareTerminal,
  IconStar as Star,
  IconSun as Sun,
  IconTerminal as Terminal,
  IconClockHour4 as Timer,
  IconTrash as Trash,
  IconTrash as Trash2,
  IconTypography as Type,
  IconArrowBackUp as Undo2,
  IconUser as User,
  IconUsers as Users,
  IconVariable as Variable,
  IconVideo as Video,
  IconWallet as Wallet,
  IconWand as Wand2,
  IconWifiOff as WifiOff,
  IconLetterW as WholeWord,
  IconAffiliate as Workflow,
  IconX as X,
  IconX as XIcon,
  IconBolt as Zap,
} from "@tabler/icons-react";
import type { TablerIcon } from "@tabler/icons-react";

export type LucideIcon = TablerIcon;

export type AnimatedIconProps = ComponentProps<TablerIcon> & {
  icon: TablerIcon;
  interaction?: "lift" | "pulse" | "spin" | "nudge";
};

export function AnimatedIcon({ icon: Icon, interaction = "lift", className = "", ...props }: AnimatedIconProps) {
  const motion =
    interaction === "spin"
      ? "transition-transform duration-200 group-hover:rotate-45 group-active:rotate-90"
      : interaction === "pulse"
        ? "transition-transform duration-200 group-hover:scale-110 group-active:scale-95"
        : interaction === "nudge"
          ? "transition-transform duration-200 group-hover:translate-x-0.5 group-active:translate-x-1"
          : "transition-transform duration-200 group-hover:-translate-y-0.5 group-active:translate-y-0 group-active:scale-95";

  return <Icon className={`${motion} ${className}`.trim()} {...props} />;
}

export {
  Accessibility,
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowDownToLine,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpFromLine,
  Bell,
  BookOpen,
  Bot,
  Box,
  Boxes,
  Braces,
  Brain,
  Bug,
  CaseSensitive,
  Check,
  CheckCircle2,
  CheckIcon,
  ChevronDown,
  ChevronDownIcon,
  ChevronRight,
  ChevronRightIcon,
  ChevronUp,
  ChevronUpIcon,
  Circle,
  CircleDashed,
  CircleHelp,
  ClipboardList,
  ClipboardPaste,
  Clock,
  Cloud,
  CloudDownload,
  CloudUpload,
  Code2,
  Coins,
  Columns2,
  Command,
  Component,
  Copy,
  Crosshair,
  Database,
  Diff,
  Eraser,
  ExternalLink,
  Eye,
  FileCode,
  FileCode2,
  FileDiff,
  FileJson,
  FileMinus,
  FilePenLine,
  FilePlus,
  FilePlus2,
  FileText,
  FileWarning,
  Folder,
  FolderGit2,
  FolderKanban,
  FolderOpen,
  FolderPlus,
  FolderSearch,
  FolderTree,
  FunctionSquare,
  Gauge,
  GitBranch,
  GitCommitHorizontal,
  GitCompareArrows,
  GitGraph,
  GitMerge,
  GitPullRequest,
  Globe,
  GripVertical,
  Hand,
  Hash,
  HelpCircle,
  History,
  Home,
  Image,
  Info,
  Keyboard,
  Layers,
  Layout,
  LayoutGrid,
  LayoutPanelLeft,
  LayoutTemplate,
  LifeBuoy,
  LineChart,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  Maximize2,
  Menu,
  MessageSquare,
  MessageSquarePlus,
  Minimize2,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreHorizontalIcon,
  MousePointer2,
  MousePointerClick,
  Palette,
  PanelBottom,
  PanelBottomClose,
  PanelLeft,
  PanelLeftClose,
  PanelLeftExpand,
  PanelRight,
  PanelRightCollapse,
  PanelRightExpand,
  Paperclip,
  Pencil,
  Pin,
  PinOff,
  Play,
  Plug,
  Plus,
  Radio,
  Redo2,
  RefreshCw,
  Regex,
  Replace,
  Rocket,
  RotateCcw,
  Rows2,
  Save,
  Scissors,
  ScrollText,
  Search,
  Settings,
  Settings2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Skull,
  SlidersHorizontal,
  Sparkles,
  Square,
  SquareArrowOutUpRight,
  SquareStack,
  SquareTerminal,
  Star,
  Sun,
  Terminal,
  Timer,
  Trash,
  Trash2,
  Type,
  Undo2,
  User,
  Users,
  Variable,
  Video,
  Wallet,
  Wand2,
  WifiOff,
  WholeWord,
  Workflow,
  X,
  XIcon,
  Zap,
};
