/*
 * Generated by scripts/contracts/generate.mjs from contracts/contract-registry.json.
 * Do not edit directly; update the contract inputs and rerun npm run generate.
 */

export const CONTRACT_NAME = "lens.contract-probe" as const;
export const CONTRACT_VERSION = "1.0.0" as const;
export const CONTRACT_OWNER = "contract-probe-owner" as const;
export const CONTRACT_CLIENT_WORKLOAD = "employee-bff" as const;
export const CONTRACT_SOURCE_DIGEST = "sha256:ad5fd34cf9201949de0bff166a6321886bde303cbe945ed16f8d8f96bec394d3" as const;

export const ERROR_CODES = ["INVALID_ARGUMENT","UNAUTHENTICATED","FORBIDDEN","STALE_AUTHORITY","CONFLICT","NOT_FOUND_OR_NOT_DISCLOSABLE","RATE_LIMITED","OVERLOADED","DEPENDENCY_UNAVAILABLE","DEADLINE_EXCEEDED","CANCELLED","AMBIGUOUS_OUTCOME","QUARANTINED","EVIDENCE_REQUIRED","INTERNAL"] as const;
export type ContractErrorCode = (typeof ERROR_CODES)[number];

export type DataClassification =
  | "public"
  | "internal"
  | "confidential"
  | "restricted";

export interface SafeContractError {
  code: ContractErrorCode;
  message: string;
  correlationId: string;
  retryable: boolean;
  retryAfterMs?: number;
}

export class ContractError extends Error implements SafeContractError {
  readonly name = "ContractError";

  constructor(
    readonly code: ContractErrorCode,
    message: string,
    readonly correlationId: string,
    readonly retryable: boolean,
    readonly retryAfterMs?: number,
  ) {
    super(message);
  }
}

export interface ContractProbeInput {
  operationId: string;
  correlationId: string;
  idempotencyKey: string;
  deadlineAt: string;
  payload: Record<string, string>;
}

export interface ContractProbeResponse {
  requestId: string;
  operationId: string;
  correlationId: string;
  classification: DataClassification;
  acceptedAt: string;
  replayed: boolean;
}

/** Internal-only envelope created by Gateway after client admission. */
export interface GatewayContractProbeRequest extends ContractProbeInput {
  requestId: string;
}

export interface ContractProbeOwnerHandler {
  submitAcceptedContractProbe(
    input: GatewayContractProbeRequest,
    signal?: AbortSignal,
  ): Promise<ContractProbeResponse>;
}

export interface ContractProbeTransport {
  submitContractProbe(
    input: ContractProbeInput,
    signal?: AbortSignal,
  ): Promise<ContractProbeResponse>;
}

export class LensContractClient {
  constructor(private readonly transport: ContractProbeTransport) {}

  submitContractProbe(
    input: ContractProbeInput,
    signal?: AbortSignal,
  ): Promise<ContractProbeResponse> {
    return this.transport.submitContractProbe(input, signal);
  }
}

export interface ContractEventEnvelope {
  eventId: string;
  aggregateType: string;
  aggregateId: string;
  aggregateSequence: number;
  eventType: string;
  schemaVersion: typeof CONTRACT_VERSION;
  occurredAt: string;
  committedAt: string;
  producerWorkloadId: string;
  sourceTransactionRef: string;
  classification: DataClassification;
  payloadDigest: `sha256:${string}`;
  traceId: string;
  operationId: string;
}
