# Generated by scripts/contracts/rag-generate.mjs from contracts/rag/*.v1.schema.json. Do not edit directly.
from dataclasses import dataclass, field
from typing import List, Literal, Optional

RAG_CONTRACT_VERSION: str = "1.0.0"
SCHEMA_DIGESTS = {
    "authorization-manifest.v1.schema.json": "292ba2c25871afe624d3ae9463bfa0ad351515c97045a330de13e44c410b346f",
    "error.v1.schema.json": "be45bdc004ed47d4361c389169bbbba7d43faf21e655989634176133b8e7bec1",
    "request.v1.schema.json": "1fdfd8d2f1ded75d79fac0b8847c213fd48495b9f9da0505b60bb4faa812c64a",
    "retrieval-request.v1.schema.json": "12b7564cda93e7499ee33d75bcdefd2d31ffb5964e5ca1f1d2cf52325dda80e2",
    "retrieval-result.v1.schema.json": "c12586d2345c8dca11b8ebdee78d556cf1ab0af3ca9449873116fc388ea69595",
    "retrieved-context.v1.schema.json": "3862455bf881c958d2239f892887c70a1d7f6793b8377d5d130fe85ceb1be037",
    "retrieved-source.v1.schema.json": "bd31df7ec7c655e1d916fe87c3f58d25c71b401bb9149dcfc7b7da3b31b2cf02",
  }

ClassificationRef = Literal["public", "internal", "confidential", "restricted"]
RetrievalStatus = Literal["context", "no_context", "denied_policy", "failed_downstream"]
RetrievalMode = Literal["lexical", "semantic", "graph", "hybrid", "structured", "citation_refresh"]
RagErrorCode = Literal[
    "INVALID_ARGUMENT", "UNAUTHENTICATED", "FORBIDDEN", "STALE_AUTHORITY",
    "RATE_LIMITED", "OVERLOADED", "DEPENDENCY_UNAVAILABLE", "DEADLINE_EXCEEDED",
    "CANCELLED", "NOT_FOUND_OR_NOT_DISCLOSABLE", "QUARANTINED",
]


@dataclass(frozen=True)
class RetrievedSource:
    document_version_ref: str
    chunk_ref: str
    content_digest: str
    citation_anchor: str
    classification_ref: ClassificationRef


@dataclass(frozen=True)
class RetrievedContext(RetrievedSource):
    text: str


@dataclass(frozen=True)
class AuthorizationManifest:
    digest: str
    retrieved_at: int
    source_revision_digest: str
    operation_decision_ref: str
    candidate_decision_ref: str
    policy_revision: int
    subject_security_revision: int
    resource_security_revision_digest: str
    profile_version: int
    profile_digest: str
    expires_at: int
    sources: List[RetrievedSource]


@dataclass(frozen=True)
class RetrievalRequest:
    request_id: str
    turn_id: str
    caller_workload_ref: Literal["ai-orchestrator"]
    subject_ref: str
    session_ref: str
    device_ref: str
    application_id: Literal["lens-employee-client"]
    query_digest: str
    query_text: str
    purpose_ref: str
    retrieval_class: Literal["enterprise-grounded"]
    corpus_ref: str
    mode: RetrievalMode
    profile_version: int
    profile_digest: str
    candidate_limit: int
    deadline_at: int
    cancellation: bool
    bulkhead: Literal["interactive", "management"]
    visibility_minimum: int


@dataclass(frozen=True)
class RetrievalResult:
    status: RetrievalStatus
    retrieval_id: Optional[str] = None
    request_id: Optional[str] = None
    turn_id: Optional[str] = None
    visibility_sequence: Optional[int] = None
    index_generation: Optional[str] = None
    context_digest: Optional[str] = None
    profile_version: Optional[int] = None
    profile_digest: Optional[str] = None
    manifest: Optional[AuthorizationManifest] = None
    sources: List[RetrievedContext] = field(default_factory=list)


@dataclass(frozen=True)
class RagError:
    error: Literal["RAG_REQUEST_FAILED"]
    code: RagErrorCode
    message: str
    retryable: bool
    retry_after_ms: Optional[int] = None
    correlation_id: str = ""
