import { describe, expect, it } from "vitest";
import { PolicyDecisionPoint, PdpError } from "../../services/pdp/PolicyDecisionPoint";
import { PolicyStore } from "../../services/pdp/PolicyStore";

describe("M03 PDP", () => {
  const signer = { sign: () => "signed-fence", verify: (fence: { signature: string }) => fence.signature === "signed-fence" };
  const pdp = () => { let now = 1_000; const service = new PolicyDecisionPoint({ subject: () => ({ revision: 3, active: true, groups: ["staff"] }), device: () => ({ revision: 5, compliant: true }), resources: (refs) => refs.map((resourceRef, index) => ({ resourceRef, revision: index + 1, published: true, integrityValid: true, aclAllows: resourceRef !== "denied" })) }, { admitDecision: () => ({ receiptDigest: "audit" }) }, signer, () => now); service.activate({ revision: 1, digest: "sha256:policy", signed: true, evaluate: () => true }, { independent: true, auditAdmitted: true, compatibilityPassed: true }); return { service, setNow: (value: number) => { now = value; } }; };
  const request = (overrides = {}) => ({ requestId: "r1", callerWorkloadRef: "retrieval", subjectRef: "s", deviceRef: "d", action: "document.read", resourceRefs: ["allowed", "denied"], normalizedContextDigest: "sha256:context", deadlineAt: 2_000, ...overrides });
  it("uses one current fact snapshot and issues a one-use revision-bound allow fence", () => { const { service } = pdp(); const decision = service.decideBatch(request()); expect(decision.allowed).toEqual(["allowed"]); const consumption = { requestId: "r1", callerWorkloadRef: "retrieval", action: "document.read", useBoundary: "operation" as const, normalizedContextDigest: "sha256:context", resourceRefs: ["allowed"] }; service.consumeFence(decision.fence!, consumption); expect(() => service.consumeFence(decision.fence!, consumption)).toThrow(PdpError); });
  it("rejects partial oversized batches before authorization", () => { const { service } = pdp(); expect(() => service.decideBatch(request({ requestId: "r2", resourceRefs: Array.from({ length: 1001 }, (_, index) => String(index)) }))).toThrow("BATCH_LIMIT_EXCEEDED"); });
  it("fails closed when the owner revision keeps changing", () => { let count = 0; const service = new PolicyDecisionPoint({ subject: () => ({ revision: 1, active: true, groups: [] }), device: () => ({ revision: 1, compliant: true }), resources: (refs) => refs.map((resourceRef) => ({ resourceRef, revision: 1, published: true, integrityValid: true, aclAllows: true })), revisionHead: () => String(++count) }, { admitDecision: () => ({ receiptDigest: "audit" }) }, signer); service.activate({ revision: 1, digest: "policy", signed: true, evaluate: () => true }, { independent: true, auditAdmitted: true, compatibilityPassed: true }); expect(() => service.decideBatch(request({ requestId: "r3", resourceRefs: ["a"], deadlineAt: Date.now() + 1000 }))).toThrow("AUTHORIZATION_STATE_CHANGED"); });
  it("activates only immutable, reviewed policy evidence and writes an outbox record", () => { const store = new PolicyStore(); store.insert({ digest: "sha256:policy", policyRevision: 1, signed: true, schemaValid: true, staticAnalysisPassed: true, testsPassed: true, evidenceRefs: ["eval:1"], authorRef: "author", reviewerRef: "reviewer" }); store.advance("sha256:policy", "schema_validated"); store.advance("sha256:policy", "evaluated"); store.advance("sha256:policy", "security_approved"); expect(store.activate("sha256:policy", { operatorRef: "release", privilegedChangeFence: "fence", auditReceipt: "audit", compatibilityPassed: true }).state).toBe("active"); expect(store.outbox).toHaveLength(1); });
});
