import { describe, expect, it } from "vitest";
import { MemoryAuthority, MemoryError } from "../../services/memory/MemoryAuthority";

describe("M04 Memory authority", () => {
  const memory = () => new MemoryAuthority({ authorize: () => ({ decisionRef: "pdp:allow" }) }, { admit: () => ({ receipt: "audit:receipt" }) }, { verifyBlob: () => true, verifyRunClose: () => true }, { verifyFinalization: () => true, commitRedisclosure: () => true, authorizeRepair: () => true });
  const begin = (service: MemoryAuthority) => service.begin({ requestId: "req-1", subjectRef: "subject-1", conversationId: "conversation-1", userContentRef: "blob:user", userContentHash: "sha256:user", idempotencyKey: "idem-1", expectedConversationRevision: 0 });
  const completed = (service: MemoryAuthority) => { const turn = begin(service); const generating = service.startGeneration(turn.turnId, turn.generationFence); return service.finalize({ turnId: turn.turnId, requestId: "req-1", subjectRef: "subject-1", expectedGenerationFence: generating.generationFence, terminal: "COMPLETED", finalizationGeneration: 1, outputRef: "blob:output", outputHash: "sha256:output", blobCommitProof: "quorum-proof", agentRunId: "run-1", agentRunCloseRef: "close-1", agentRunFinalRevision: 2, counterDigest: "sha256:counters", derivedDisclosureManifestRef: "manifest-1", releaseFenceRef: "release-fence", guardEvidenceRefs: ["guard-1"], disclosureReservationRef: "reservation-1" }); };
  it("commits durable intent before finalization and allocates ordered turn state", () => { const service = memory(); const turn = begin(service); expect(turn.state).toBe("INTENT_COMMITTED"); expect(turn.sequence).toBe(1); expect(service.outbox[0]?.eventType).toBe("turn.intent_committed"); const final = completed(service); expect(final.state).toBe("COMPLETED"); expect(service.getTurn({ requestId: "req-status", subjectRef: "subject-1", turnId: final.turnId })).not.toHaveProperty("outputRef"); });
  it("is idempotent only for the same actor and canonical intent", () => { const service = memory(); const first = begin(service); const replay = begin(service); expect(replay.turnId).toBe(first.turnId); expect(() => service.begin({ requestId: "req-2", subjectRef: "subject-1", conversationId: "conversation-1", userContentRef: "blob:user", userContentHash: "sha256:changed", idempotencyKey: "idem-1", expectedConversationRevision: 1 })).toThrow("IDEMPOTENCY_CONFLICT"); });
  it("rejects stale finalizers and missing immutable output evidence", () => { const service = memory(); const turn = begin(service); service.startGeneration(turn.turnId, turn.generationFence); expect(() => service.finalize({ turnId: turn.turnId, requestId: "req-1", subjectRef: "subject-1", expectedGenerationFence: turn.generationFence, terminal: "COMPLETED", finalizationGeneration: 1 })).toThrow(MemoryError); });
  it("requires fresh authorization, exposure commit, and audit admission for output re-disclosure", () => { const service = memory(); const turn = completed(service); const disclosure = { requestId: "req-2", subjectRef: "subject-1", turnId: turn.turnId, deviceRef: "device-1", purposeRef: "history", disclosureReservationRef: "reservation-2", releaseFenceRef: "release-fence-2" }; expect(service.rediscloseOutput(disclosure).outputHash).toBe("sha256:output"); expect(service.repairOutput({ turnId: turn.turnId, proofReadable: false, repairFenceRef: "repair-fence" }).state).toBe("DEGRADED_OUTPUT"); expect(() => service.rediscloseOutput({ ...disclosure, requestId: "req-3" })).toThrow("DURABILITY_ERROR"); });
});
