import { describe, expect, it } from "vitest";
import { UntrustedContentIntake } from "../../services/tool-sandbox/UntrustedContentIntake";

describe("M05 untrusted content isolation", () => {
  const profile = { digest: "sha256:profile", imageDigest: "sha256:image", supportedTypes: ["application/pdf"], maxInputBytes: 100, maxExpandedBytes: 1_000, maxExpansionRatio: 10, maxArchiveDepth: 4, maxArchiveMembers: 10, maxPages: 10, maxPixels: 1_000_000, maxObjects: 100, maxCpuMs: 1_000, maxMemoryBytes: 1_000_000, maxFileDescriptors: 32, maxWallMs: 2_000 };
  const sandbox = (overrides = {}) => ({ run: (input: { limits: { maxArchiveDepth: number } }) => ({ outputDigest: input.limits.maxArchiveDepth === 4 ? "sha256:output" : undefined, detectedType: "application/pdf", parserCrashed: false, isolationEvidenceValid: true, microvmDestroyed: true, outputValidated: true, ...overrides }) });
  const intake = (sandboxOverrides = {}) => new UntrustedContentIntake({ inspect: () => ({ detectedType: "application/pdf", malwareDetected: false, activeContent: false, externalReference: false, encryptedArchive: false }) }, { verify: () => true }, sandbox(sandboxOverrides));
  it("accepts a verified supported file only after disposable microVM evidence", () => { expect(intake().submit({ inputRef: "object:1", contentDigest: "sha256:input", byteLength: 10, declaredType: "application/pdf", profile }).status).toBe("ACCEPTED"); });
  it("quarantines type confusion before any parser launch", () => { const service = new UntrustedContentIntake({ inspect: () => ({ detectedType: "application/zip", malwareDetected: false, activeContent: false, externalReference: false, encryptedArchive: false }) }, { verify: () => true }, sandbox()); expect(service.submit({ inputRef: "object:2", contentDigest: "sha256:input", byteLength: 10, declaredType: "application/pdf", profile }).reason).toBe("TYPE_MISMATCH"); });
  it("quarantines archive/limit attacks and never accepts missing isolation cleanup", () => { expect(intake({ limitHit: "archive_depth" }).submit({ inputRef: "object:3", contentDigest: "sha256:input", byteLength: 10, declaredType: "application/pdf", profile }).reason).toBe("EXPANSION_LIMIT"); expect(intake({ microvmDestroyed: false }).submit({ inputRef: "object:4", contentDigest: "sha256:input", byteLength: 10, declaredType: "application/pdf", profile }).reason).toBe("ISOLATION_VIOLATION"); });
  it("makes duplicate content deterministic and never retries a quarantined digest with weaker handling", () => { const service = intake({ limitHit: "archive_depth" }); const first = service.submit({ inputRef: "object:5", contentDigest: "sha256:poison", byteLength: 10, declaredType: "application/pdf", profile }); const replay = service.submit({ inputRef: "object:changed-location", contentDigest: "sha256:poison", byteLength: 10, declaredType: "application/pdf", profile }); expect(replay).toEqual(first); expect(service.quarantine).toHaveLength(1); });
});
