import { describe, expect, it } from "vitest";
import { ModelRegistry, RegistryError } from "../../services/model-registry/ModelRegistry";

describe("M07 Model Registry", () => {
  const registry = () => new ModelRegistry({ admit: () => ({ receipt: "audit" }) }, { sign: () => "signed-snapshot" }, { verify: () => true }, { verify: () => true }, () => 100);
  const register = (service: ModelRegistry) => { service.register({ modelId: "model", version: "v1", artifactRef: "oci://internal/models/v1", artifactDigest: "sha256:artifact", manifestDigest: "sha256:manifest", provenanceRef: "provenance", sbomRef: "sbom", modelCardRef: "card", signerRef: "signer" }); service.attachCapability("model", "v1", { digest: "sha256:capability", contextWindow: 4096, supportsToolCalling: true, supportsVision: false, supportsEmbeddings: false, runtimeFamily: "llama", quantization: "int8", measuredThroughputEvidenceRef: "measure", approvedRequestClasses: ["chat"] }); };
  const evidence = (service: ModelRegistry, kind: "evaluation" | "red_team" | "privacy" | "provenance" | "security") => service.ingestEvidence({ evidenceRef: `evidence:${kind}`, artifactDigest: "sha256:artifact", kind, signed: true, passed: true, criticalFailure: false, deploymentProfileDigest: "sha256:deployment" });
  it("requires every signed evidence class and privileged approval before a model becomes routable", () => { const service = registry(); register(service); evidence(service, "evaluation"); expect(() => service.approve("model", "v1", "sha256:deployment", "fence")).toThrow("EVIDENCE_INSUFFICIENT"); (["red_team", "privacy", "provenance", "security"] as const).forEach((kind) => evidence(service, kind)); expect(service.approve("model", "v1", "sha256:deployment", "fence").state).toBe("APPROVED"); expect(service.promote("model", "v1", "sha256:deployment", "fence").state).toBe("ROUTABLE"); expect(service.snapshot(1000).signature).toBe("signed-snapshot"); });
  it("revocation supersedes aliases and removes a model from signed eligibility", () => { const service = registry(); register(service); (["evaluation", "red_team", "privacy", "provenance", "security"] as const).forEach((kind) => evidence(service, kind)); service.approve("model", "v1", "sha256:deployment", "fence"); service.promote("model", "v1", "sha256:deployment", "fence"); service.setAlias("model", "chat", "v1", "fence"); service.revoke("model", "v1", "fence"); const snapshot = service.snapshot(1000); expect(snapshot.routable).toHaveLength(0); expect(snapshot.emergencyDenyEpoch).toBe(1); });
  it("rejects rollout members that are not currently routable", () => { const service = registry(); expect(() => service.activateRollout({ rolloutId: "r1", revision: 1, capabilityDigest: "sha256:capability", members: [{ artifactDigest: "sha256:artifact", weight: 10_000 }], assignmentKey: "subject", evidenceDigest: "sha256:evidence" }, "fence")).toThrow(RegistryError); });
});
