import { describe, expect, it } from "vitest";
import { EmployeeBff } from "../../services/product-bff/EmployeeBff";

describe("M08 product BFF", () => {
  const bff = () => new EmployeeBff({ validate: () => ({ subjectRef: "subject", sessionId: "session", deviceRef: "device", sessionRevision: 1, navigationCapabilities: ["chat", "history"] }) }, { verify: () => true, digest: (output) => `sha256:${output}` }, { status: () => ({ state: "COMPLETED", turnId: "turn", conversationId: "conversation" }), redisclose: () => ({ output: "final", outputDigest: "sha256:final", citationRefs: ["citation-1"] }) }, { resolve: (input) => ({ citationRef: input.citationRef, title: "Source", versionRef: "v1", snippet: "authorized" }) }, () => 100);
  const session = { sessionId: "session", deviceRef: "device", clientKeyRef: "key", csrfToken: "csrf" };
  it("never sends protected bytes in live progress and accepts only an exact final release envelope", () => { const service = bff(); expect(service.progress({ ...session, turnId: "turn", state: "GENERATING" })).toEqual({ type: "progress", turnId: "turn", state: "GENERATING" }); expect(service.release({ ...session, requestId: "request", output: "final", citations: ["citation-1"], envelope: { requestId: "request", turnId: "turn", callerWorkloadRef: "product-bff", outputDigest: "sha256:final", byteLength: 5, expiresAt: 200, derivedDisclosureRef: "derived", auditReceipt: "audit", finalizationRef: "finalized", exposureCommitRef: "committed", signature: "signature" } }).type).toBe("final"); });
  it("rejects a digest-mismatched release before output reaches the client", () => { expect(() => bff().release({ ...session, requestId: "request", output: "final", citations: [], envelope: { requestId: "request", turnId: "turn", callerWorkloadRef: "product-bff", outputDigest: "sha256:other", byteLength: 5, expiresAt: 200, derivedDisclosureRef: "derived", auditReceipt: "audit", finalizationRef: "finalized", exposureCommitRef: "committed", signature: "signature" } })).toThrow("RELEASE_ENVELOPE_INVALID"); });
  it("reopens through fresh Memory re-disclosure and resolves citations server-side", () => { const service = bff(); expect(service.reopen({ ...session, requestId: "request", turnId: "turn", purposeRef: "history" }).citations).toEqual(["citation-1"]); expect(service.citation({ ...session, requestId: "request", citationRef: "citation-1" }).versionRef).toBe("v1"); });
});
