import { describe, expect, it } from "vitest";
import { AgentError, AgentRuntime } from "../../services/agent-runtime/AgentRuntime";

describe("M09 Agent Runtime", () => {
  const runtime = () => { const service = new AgentRuntime({ authorize: () => true }, () => 10); service.registerTool({ toolId: "ticket.read", version: "1", targetProfileDigest: "sha256:target", risk: "read", requiresApproval: false, idempotentReplay: true, schemaDigest: "sha256:schema", dataFlowProfileDigest: "sha256:flow" }); service.registerTool({ toolId: "ticket.write", version: "1", targetProfileDigest: "sha256:target", risk: "reversible_write", requiresApproval: true, idempotentReplay: false, schemaDigest: "sha256:schema", dataFlowProfileDigest: "sha256:flow" }); return service; };
  const begin = (service: AgentRuntime) => service.begin({ requestId: "request", subjectRef: "subject", deviceRef: "device", applicationRef: "app", envelope: { maxSteps: 2, maxSideEffects: 1, maxCostUnits: 10, deadlineAt: 100, workflowProfileDigest: "sha256:workflow", budgetDecisionRef: "budget" } });
  it("conservatively consumes immutable run bounds and rejects revision/payload drift", () => { const service = runtime(); const run = begin(service); const fence = service.reserveStep({ runId: run.runId, expectedRevision: run.revision, stepId: "step-1", toolId: "ticket.read", toolVersion: "1", intentDigest: "sha256:intent", declaredCostUnits: 4 }); expect(() => service.reserveStep({ runId: run.runId, expectedRevision: run.revision, stepId: "step-1", toolId: "ticket.read", toolVersion: "1", intentDigest: "sha256:changed", declaredCostUnits: 4 })).toThrow("INTENT_CONFLICT"); service.start({ fence, consumerAttemptId: "attempt", exactIntentDigest: "sha256:intent", policyEpoch: 1 }); const finalized = service.finalize({ runId: run.runId, stepId: "step-1", state: "SUCCEEDED" }); expect(service.close(run.runId, finalized.revision, "COMPLETED").run.state).toBe("COMPLETED"); });
  it("binds approval to the exact intent, a different approver, and one use", () => { const service = runtime(); const run = begin(service); const fence = service.reserveStep({ runId: run.runId, expectedRevision: run.revision, stepId: "step-2", toolId: "ticket.write", toolVersion: "1", intentDigest: "sha256:write", declaredCostUnits: 5 }); const approval = service.approve({ runId: run.runId, stepId: "step-2", actorRef: "actor", approverRef: "reviewer", intentDigest: "sha256:write", policyEpoch: 1, expiresAt: 90 }); service.start({ fence, consumerAttemptId: "attempt", exactIntentDigest: "sha256:write", policyEpoch: 1, approvalId: approval.approvalId }); expect(() => service.start({ fence, consumerAttemptId: "other", exactIntentDigest: "sha256:write", policyEpoch: 1, approvalId: approval.approvalId })).toThrow(AgentError); });
  it("does not close completed while an ambiguous side effect remains", () => { const service = runtime(); const run = begin(service); const fence = service.reserveStep({ runId: run.runId, expectedRevision: run.revision, stepId: "step-3", toolId: "ticket.read", toolVersion: "1", intentDigest: "sha256:read", declaredCostUnits: 1 }); service.start({ fence, consumerAttemptId: "attempt", exactIntentDigest: "sha256:read", policyEpoch: 1 }); const final = service.finalize({ runId: run.runId, stepId: "step-3", state: "OUTCOME_UNKNOWN" }); expect(() => service.close(run.runId, final.revision, "COMPLETED")).toThrow("CLOSE_BLOCKED"); });
});
