import { describe, expect, it } from "vitest";
import { RecoveryCoordinator, RecoveryError, type PrivilegedChangeFence, type RestoreProof } from "../../platform/dr/RecoveryCoordinator";

const digest = (name: string) => `sha256:${name}`;
const proof = (): RestoreProof => ({ evidenceManifestDigest: digest("evidence"), independentReviewerRef: "reviewer", auditContinuous: true, secretsManifestCurrent: true, keyAndRevocationEpochsCurrent: true, recoveryShareQuorum: true, authorityHeadsRestored: true, currentArtifactsAdmitted: true, nodesReattested: true, abuseRegressionPassed: true, ambiguousPreFailoverWorkFrozen: true, ownerReconciliationComplete: true, restoreCellNoPublicRoute: true, restoreCellNoCorporateRoute: true, restoreCellNoProductionRoute: true, restoreCellNoExportRoute: true, plaintextZeroizedOrQuarantined: true, auditAdmissionReceipt: "audit-recovery" });
const fence = (targetIdentity: PrivilegedChangeFence["targetIdentity"], operation: PrivilegedChangeFence["operation"], canonicalPayloadDigest: string, nonce = `${targetIdentity}-${operation}`): PrivilegedChangeFence => ({ fenceId: `fence-${nonce}`, fenceDigest: digest(`fence-${nonce}`), subjectRef: "selector", deviceRef: "device", independentApproverRef: "approver", targetIdentity, operation, canonicalPayloadDigest, expiresAt: 100, nonce, auditAdmissionReceipt: "audit-fence" });
const service = (verified = proof()) => new RecoveryCoordinator({ verify: () => ({ declarationEvidenceDigest: digest("declaration-evidence"), commanderRef: "commander" }) }, { execute: () => ({ targetReceipt: "target", targetEvidenceDigest: digest("containment") }) }, { verify: () => verified }, { reopen: () => ({ targetReceipt: "traffic", targetEvidenceDigest: digest("traffic") }) }, () => 10);
const incident = { incidentId: "incident-1", scopeDigest: digest("scope"), signedDeclarationDigest: digest("declaration"), auditAdmissionReceipt: "audit-incident" };
const begin = (coordinator: RecoveryCoordinator, checkpointAgeSeconds = 60) => { coordinator.contain(incident, [{ owner: "identity", action: "revoke", targetDigest: digest("identity") }, { owner: "agent-runtime", action: "freeze", targetDigest: digest("runs") }]); const restoreIntentDigest = digest("restore-intent"); return coordinator.beginRestore({ incidentId: incident.incidentId, backupSetDigest: digest("backup"), recoveryManifestDigest: digest("manifest"), checkpointAgeSeconds, restoreIntentDigest, restoreFence: fence("backup", "restore.select", restoreIntentDigest), selectorRef: "selector", approverRef: "approver" }); };

describe("M10 Recovery Coordinator", () => {
  it("coordinates declared containment and opens traffic only after current complete clean-room proof", () => { const coordinator = service(); const restore = begin(coordinator); expect(coordinator.verifyRestore(restore.restoreId).state).toBe("RESTORE_VERIFIED"); const reopenIntentDigest = digest("reopen-intent"); expect(coordinator.reopenTraffic({ restoreId: restore.restoreId, reopenIntentDigest, reopenFence: fence("traffic-gate", "traffic.reopen", reopenIntentDigest) }).state).toBe("TRAFFIC_REOPENED"); const cleanupIntentDigest = digest("cleanup-intent"); expect(coordinator.closeRestore({ restoreId: restore.restoreId, cleanupIntentDigest, cleanupFence: fence("restore-cell", "restore.cleanup", cleanupIntentDigest), signedAcceptanceDigest: digest("accept"), zeroized: true, quarantined: false }).state).toBe("CLOSED"); });
  it("rejects a single actor selecting and approving a restore", () => { const coordinator = service(); coordinator.contain(incident, [{ owner: "identity", action: "revoke", targetDigest: digest("identity") }]); const restoreIntentDigest = digest("restore-intent"); expect(() => coordinator.beginRestore({ incidentId: incident.incidentId, backupSetDigest: digest("backup"), recoveryManifestDigest: digest("manifest"), checkpointAgeSeconds: 1, restoreIntentDigest, restoreFence: fence("backup", "restore.select", restoreIntentDigest), selectorRef: "operator", approverRef: "operator" })).toThrow("RESTORE_INVALID"); });
  it("fails closed for an overdue Class A checkpoint or any missing route boundary", () => { const coordinator = service(); const stale = begin(coordinator, 61); expect(() => coordinator.verifyRestore(stale.restoreId)).toThrow(RecoveryError); const unsafe = service({ ...proof(), restoreCellNoProductionRoute: false }); const restore = begin(unsafe); expect(() => unsafe.verifyRestore(restore.restoreId)).toThrow("RECOVERY_INCOMPLETE"); });
  it("rejects expired, mismatched, and replayed privileged fences", () => { const coordinator = service(); const restoreIntentDigest = digest("restore-intent"); coordinator.contain(incident, [{ owner: "identity", action: "revoke", targetDigest: digest("identity") }]); expect(() => coordinator.beginRestore({ incidentId: incident.incidentId, backupSetDigest: digest("backup"), recoveryManifestDigest: digest("manifest"), checkpointAgeSeconds: 1, restoreIntentDigest, restoreFence: { ...fence("backup", "restore.select", restoreIntentDigest), expiresAt: 10 }, selectorRef: "selector", approverRef: "approver" })).toThrow("FENCE_INVALID"); const restore = begin(coordinator); coordinator.verifyRestore(restore.restoreId); const reopenIntentDigest = digest("reopen-intent"); const reusable = fence("traffic-gate", "traffic.reopen", reopenIntentDigest, "reopen-once"); coordinator.reopenTraffic({ restoreId: restore.restoreId, reopenIntentDigest, reopenFence: reusable }); expect(() => coordinator.reopenTraffic({ restoreId: restore.restoreId, reopenIntentDigest, reopenFence: reusable })).toThrow("TRAFFIC_BLOCKED"); });
  it("does not open traffic if evidence changes after verification", () => { let current = proof(); const coordinator = service(); const dynamic = new RecoveryCoordinator({ verify: () => ({ declarationEvidenceDigest: digest("declaration-evidence"), commanderRef: "commander" }) }, { execute: () => ({ targetReceipt: "target", targetEvidenceDigest: digest("containment") }) }, { verify: () => current }, { reopen: () => ({ targetReceipt: "traffic", targetEvidenceDigest: digest("traffic") }) }, () => 10); const restore = begin(dynamic); dynamic.verifyRestore(restore.restoreId); current = { ...current, auditContinuous: false }; const reopenIntentDigest = digest("reopen-intent"); expect(() => dynamic.reopenTraffic({ restoreId: restore.restoreId, reopenIntentDigest, reopenFence: fence("traffic-gate", "traffic.reopen", reopenIntentDigest) })).toThrow("TRAFFIC_BLOCKED"); void coordinator; });
});
