export interface SessionAuditPort { admitSession(event: "issued" | "revoked", sessionId: string, subjectRef: string, deviceRef: string): { receiptDigest: string }; }
export class SessionError extends Error { constructor(readonly code: "session_not_found" | "session_revoked" | "session_expired" | "device_binding_mismatch" | "client_key_binding_mismatch" | "idempotency_conflict") { super(code); } }
export interface SessionContext { subjectRef: string; deviceRef: string; clientKeyRef: string; authenticationMethodRef: string; expiresAt: number; }
interface Session extends SessionContext { sessionId: string; revision: number; revoked: boolean; }
/** Opaque device/key-bound session authority; authentication context has no authorization facts. */
export class SessionAuthority {
  private readonly sessions = new Map<string, Session>(); private readonly idempotency = new Map<string, { sessionId: string; digest: string }>(); readonly outbox: { eventId: string; sessionId: string; revision: number; auditReceipt: string }[] = [];
  constructor(private readonly audit: SessionAuditPort, private readonly now = () => Date.now(), private readonly nextId = (() => { let value = 0; return () => `session-${++value}`; })()) {}
  issue(context: SessionContext, idempotencyKey: string): { sessionId: string; revision: number } { if (context.expiresAt <= this.now()) throw new SessionError("session_expired"); const digest = `${context.subjectRef}:${context.deviceRef}:${context.clientKeyRef}:${context.authenticationMethodRef}:${context.expiresAt}`; const replay = this.idempotency.get(idempotencyKey); if (replay) { if (replay.digest !== digest) throw new SessionError("idempotency_conflict"); const value = this.sessions.get(replay.sessionId)!; return { sessionId: value.sessionId, revision: value.revision }; } const sessionId = this.nextId(); const receipt = this.audit.admitSession("issued", sessionId, context.subjectRef, context.deviceRef); this.sessions.set(sessionId, { ...context, sessionId, revision: 1, revoked: false }); this.idempotency.set(idempotencyKey, { sessionId, digest }); this.outbox.push({ eventId: `session:${sessionId}:issued`, sessionId, revision: 1, auditReceipt: receipt.receiptDigest }); return { sessionId, revision: 1 }; }
  validate(sessionId: string, deviceRef: string, clientKeyRef: string): Omit<Session, "clientKeyRef" | "revoked"> { const session = this.sessions.get(sessionId); if (!session) throw new SessionError("session_not_found"); if (session.revoked) throw new SessionError("session_revoked"); if (session.expiresAt <= this.now()) throw new SessionError("session_expired"); if (session.deviceRef !== deviceRef) throw new SessionError("device_binding_mismatch"); if (session.clientKeyRef !== clientKeyRef) throw new SessionError("client_key_binding_mismatch"); const { clientKeyRef: _, revoked: __, ...context } = session; return context; }
  revoke(sessionId: string): void { const session = this.sessions.get(sessionId); if (!session) throw new SessionError("session_not_found"); if (session.revoked) return; const receipt = this.audit.admitSession("revoked", sessionId, session.subjectRef, session.deviceRef); session.revoked = true; session.revision += 1; this.outbox.push({ eventId: `session:${sessionId}:revoked`, sessionId, revision: session.revision, auditReceipt: receipt.receiptDigest }); }
}
